import type { AcaoDoSistema } from "../m16-travamento/acoes.js";

/**
 * M35 — O CATÁLOGO COMERCIAL: quais MÓDULOS existem para contratar, e a que módulo cada
 * ação do sistema pertence (V10 T1 · N6.1).
 *
 * ═══ ⚠️ ISTO NÃO É UM SEGUNDO CENSO DE PERMISSÕES ═══
 * Permissão responde "este usuário pode?". Habilitação responde "este município
 * CONTRATOU?". São perguntas diferentes, com donos diferentes — a permissão é do
 * administrador do ente, a habilitação é do fornecedor — e por isso NÃO se misturam numa
 * tabela só. Um servidor com a ação `EMPENHAR` num ente que não contratou o núcleo contábil
 * continua sem empenhar, e o motivo que ele lê é o certo.
 *
 * ═══ ⚠️ O `Record` EXAUSTIVO É A REDE, e ela já provou o valor no `AREA_DA_ACAO` ═══
 * `MODULO_DA_ACAO` é `Record<AcaoDoSistema, ModuloComercial>`. Uma ação nova no censo do
 * M16 NÃO COMPILA até alguém dizer a que módulo comercial ela pertence. Uma lista por
 * módulo ("o núcleo tem estas ações") aceitaria em silêncio a ação nova — e o efeito seria
 * uma funcionalidade entregue de graça, ou pior, uma funcionalidade que o gate solta porque
 * ninguém a classificou.
 *
 * ═══ ⚠️ `PLATAFORMA` NÃO É UM MÓDULO À VENDA — E NÃO É UMA GAVETA DE SOBRA ═══
 * Administração de usuários e perfis, cadastro canônico de Pessoa, suporte, anexos e
 * assinatura são a PLATAFORMA: existem em toda implantação, em qualquer contrato, e nunca
 * são suspensos. Se fossem licenciáveis, suspender o contrato tiraria do município a
 * capacidade de administrar os próprios usuários e de ler a própria auditoria — e aí a
 * suspensão comercial viraria sequestro de dados.
 */

export type ModuloComercial =
  | "NUCLEO_CONTABIL"
  | "TRIBUTOS_E_ARRECADACAO"
  | "PATRIMONIO_E_ALMOXARIFADO"
  | "COMPRAS_E_CONTRATOS"
  | "PESSOAL_E_FOLHA"
  | "ATENDIMENTO_AO_CIDADAO"
  | "TRANSPARENCIA_E_CONTROLE"
  | "INTEGRACOES_E_PRESTACAO_DE_CONTAS"
  | "PLATAFORMA";

export interface ModuloDoCatalogo {
  readonly id: ModuloComercial;
  /** O nome comercial, em linguagem do ente — nunca "M05" nem "núcleo". */
  readonly nome: string;
  readonly descricao: string;
  /**
   * Os módulos SEM OS QUAIS este não funciona. Habilitar um módulo cuja dependência não
   * está contratada é RECUSADO nomeando a dependência — nunca habilitando-a por tabela.
   */
  readonly depende: readonly ModuloComercial[];
  /** `false` só para a PLATAFORMA: ela não se contrata, não se suspende, não se vende. */
  readonly licenciavel: boolean;
}

export const CATALOGO_DE_MODULOS: readonly ModuloDoCatalogo[] = [
  {
    id: "PLATAFORMA",
    nome: "Plataforma",
    descricao:
      "Usuários, perfis e permissões, cadastro de pessoas e credores, anexos, assinatura, " +
      "campos adicionais e canais de suporte. Existe em toda implantação e não se suspende.",
    depende: [],
    licenciavel: false,
  },
  {
    id: "NUCLEO_CONTABIL",
    nome: "Contabilidade e execução orçamentária",
    descricao:
      "PPA, LDO e LOA, créditos adicionais, programação financeira, empenho, liquidação, " +
      "pagamento, restos a pagar, tesouraria, conciliação bancária, dívida fundada, " +
      "precatórios, convênios, consórcios, livros, balanços e demonstrativos fiscais.",
    depende: [],
    licenciavel: true,
  },
  {
    id: "TRIBUTOS_E_ARRECADACAO",
    nome: "Tributos e arrecadação",
    descricao:
      "Cadastro imobiliário, parâmetros tributários, lançamento e constituição de crédito, " +
      "certidões e dívida ativa.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
  {
    id: "PATRIMONIO_E_ALMOXARIFADO",
    nome: "Patrimônio e almoxarifado",
    descricao:
      "Acervo de bens, depreciação e reavaliação, inventário, movimentação, etiquetas, " +
      "estoque físico e contábil, requisições e provisões.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
  {
    id: "COMPRAS_E_CONTRATOS",
    nome: "Compras, licitações e contratos",
    descricao:
      "Solicitação de compra, pesquisa de preços, processo licitatório, contratos e aditivos, " +
      "ordens de compra e de serviço, fiscalização, medição e recebimento.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
  {
    id: "PESSOAL_E_FOLHA",
    nome: "Pessoal e folha de pagamento",
    descricao:
      "Servidores, vínculos, cargos e lotações, rubricas, cálculo da folha, encargos, " +
      "guias de recolhimento e portal do servidor.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
  {
    id: "ATENDIMENTO_AO_CIDADAO",
    nome: "Atendimento e protocolo",
    descricao:
      "Processo digital, tramitação entre setores, ouvidoria, carta de serviços, " +
      "solicitações do cidadão e comunicação interna.",
    depende: [],
    licenciavel: true,
  },
  {
    id: "TRANSPARENCIA_E_CONTROLE",
    nome: "Transparência e controle interno",
    descricao:
      "Portal da transparência, consultas públicas, auditorias internas, checklist com base " +
      "legal e relatório circunstanciado.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
  {
    id: "INTEGRACOES_E_PRESTACAO_DE_CONTAS",
    nome: "Integrações e prestação de contas",
    descricao:
      "Remessas ao tribunal de contas, importadores de folha e de tributos e integração bancária.",
    depende: ["NUCLEO_CONTABIL"],
    licenciavel: true,
  },
];

/** Os módulos que SE CONTRATAM — a PLATAFORMA fica de fora, e é o único caso. */
export const MODULOS_LICENCIAVEIS: readonly ModuloComercial[] = CATALOGO_DE_MODULOS.filter(
  (m) => m.licenciavel
).map((m) => m.id);

export function moduloDoCatalogo(id: ModuloComercial): ModuloDoCatalogo {
  const achado = CATALOGO_DE_MODULOS.find((m) => m.id === id);
  if (achado === undefined) {
    throw new Error(`MÓDULO COMERCIAL DESCONHECIDO: "${id}". Nada foi gravado.`);
  }
  return achado;
}

/** O nome comercial, para a mensagem que o servidor público lê. */
export function nomeDoModulo(id: ModuloComercial): string {
  return moduloDoCatalogo(id).nome;
}

/**
 * ⚠️ A CLASSIFICAÇÃO DE CADA AÇÃO. Gerada uma vez a partir de `AREA_DA_ACAO` e depois
 * mantida à mão, porque a área NÃO determina o módulo em todos os casos: a área "receita"
 * abriga tanto a arrecadação orçamentária (núcleo contábil) quanto o cadastro imobiliário e
 * os parâmetros tributários (tributos); a área "dívida" abriga a dívida fundada (núcleo) e a
 * dívida ativa (tributos). Classificar pela área mandaria o município que não contratou
 * tributos usar o lançamento tributário de graça.
 */
export const MODULO_DA_ACAO: Record<AcaoDoSistema, ModuloComercial> = {
  REGISTRAR_LANCAMENTO_MANUAL: "NUCLEO_CONTABIL",
  ESTORNAR_LANCAMENTO_MANUAL: "NUCLEO_CONTABIL",
  CRIAR_FICHA: "NUCLEO_CONTABIL",
  CRIAR_RECEITA_PREVISTA: "NUCLEO_CONTABIL",
  REPREVISAR_RECEITA: "NUCLEO_CONTABIL",
  CRIAR_VERSAO_CMD: "NUCLEO_CONTABIL",
  CRIAR_VERSAO_MBA: "NUCLEO_CONTABIL",
  LIBERAR_PROGRAMACAO: "NUCLEO_CONTABIL",
  CONFIGURAR_LIMITACAO_EMPENHO: "NUCLEO_CONTABIL",
  CADASTRAR_PPA: "NUCLEO_CONTABIL",
  CADASTRAR_ESTRUTURA_PPA: "NUCLEO_CONTABIL",
  CADASTRAR_PROGRAMA_PPA: "NUCLEO_CONTABIL",
  CADASTRAR_RECEITA_PPA: "NUCLEO_CONTABIL",
  CADASTRAR_LDO: "NUCLEO_CONTABIL",
  CADASTRAR_PRIORIDADE_LDO: "NUCLEO_CONTABIL",
  CADASTRAR_METAS_FISCAIS_LDO: "NUCLEO_CONTABIL",
  CADASTRAR_RISCOS_FISCAIS_LDO: "NUCLEO_CONTABIL",
  CADASTRAR_RENUNCIA_RECEITA_LDO: "NUCLEO_CONTABIL",
  CADASTRAR_ALIENACAO_LDO: "NUCLEO_CONTABIL",
  // V18/C13 — alterar a peça aprovada é planejamento, como cadastrá-la.
  ALTERAR_PLANEJAMENTO: "NUCLEO_CONTABIL",
  // V19/C05 — custo por centro é contabilidade gerencial do núcleo contábil.
  PARAMETRIZAR_RATEIO_DE_CUSTO: "NUCLEO_CONTABIL",
  APROPRIAR_CUSTO: "NUCLEO_CONTABIL",
  CRIAR_LEI_DE_CREDITO: "NUCLEO_CONTABIL",
  DECLARAR_DISPONIBILIDADE_DE_RECURSO_NOVO: "NUCLEO_CONTABIL",
  CRIAR_DECRETO_DE_CREDITO: "NUCLEO_CONTABIL",
  EXECUTAR_CREDITO: "NUCLEO_CONTABIL",
  ANULAR_CREDITO: "NUCLEO_CONTABIL",
  ENCERRAR_DECRETO: "NUCLEO_CONTABIL",
  REGISTRAR_ARRECADACAO: "NUCLEO_CONTABIL",
  ANULAR_ARRECADACAO: "NUCLEO_CONTABIL",
  RECONHECER_RECEITA: "NUCLEO_CONTABIL",
  ESTORNAR_RECONHECIMENTO: "NUCLEO_CONTABIL",
  CANCELAR_RECONHECIMENTO: "NUCLEO_CONTABIL",
  RESERVAR_DOTACAO: "NUCLEO_CONTABIL",
  LIBERAR_RESERVA: "NUCLEO_CONTABIL",
  EMPENHAR: "NUCLEO_CONTABIL",
  ANULAR_EMPENHO: "NUCLEO_CONTABIL",
  ANULAR_EMPENHO_PARCIAL: "NUCLEO_CONTABIL",
  LIQUIDAR: "NUCLEO_CONTABIL",
  ANULAR_LIQUIDACAO: "NUCLEO_CONTABIL",
  ANULAR_LIQUIDACAO_PARCIAL: "NUCLEO_CONTABIL",
  PAGAR: "NUCLEO_CONTABIL",
  PREPARAR_ORDEM_PAGAMENTO: "NUCLEO_CONTABIL",
  AUTORIZAR_ORDEM_PAGAMENTO: "NUCLEO_CONTABIL",
  CANCELAR_ORDEM_PAGAMENTO: "NUCLEO_CONTABIL",
  SOLICITAR_EMPENHO: "NUCLEO_CONTABIL",
  AUTORIZAR_SOLICITACAO_DE_EMPENHO: "NUCLEO_CONTABIL",
  ANULAR_PAGAMENTO: "NUCLEO_CONTABIL",
  ANULAR_PAGAMENTO_PARCIAL: "NUCLEO_CONTABIL",
  ESTORNAR_ANULACAO_PARCIAL: "NUCLEO_CONTABIL",
  REGISTRAR_INGRESSO_EXTRA: "NUCLEO_CONTABIL",
  REGISTRAR_DISPENDIO_EXTRA: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_EXTRA: "NUCLEO_CONTABIL",
  ABRIR_EXERCICIO: "NUCLEO_CONTABIL",
  ENCERRAR_EXERCICIO: "NUCLEO_CONTABIL",
  APURAR_RESULTADO: "NUCLEO_CONTABIL",
  ESTORNAR_APURACAO: "NUCLEO_CONTABIL",
  ENCERRAR_CONTROLES_ORCAMENTARIOS: "NUCLEO_CONTABIL",
  PARAMETRIZAR_VIRADA_DOS_CONTROLES: "NUCLEO_CONTABIL",
  ESTORNAR_ENCERRAMENTO_CONTROLES: "NUCLEO_CONTABIL",
  LIQUIDAR_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  PAGAR_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  CANCELAR_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  ANULAR_PAGAMENTO_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  ANULAR_CANCELAMENTO_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  IMPORTAR_EXTRATO: "NUCLEO_CONTABIL",
  VINCULAR_CONCILIACAO: "NUCLEO_CONTABIL",
  ESTORNAR_VINCULO: "NUCLEO_CONTABIL",
  TRANSFERIR_ENTRE_CONTAS: "NUCLEO_CONTABIL",
  REGISTRAR_MOVIMENTO_BANCARIO: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_BANCARIO: "NUCLEO_CONTABIL",
  ABRIR_CONCILIACAO: "NUCLEO_CONTABIL",
  ENCERRAR_CONCILIACAO: "NUCLEO_CONTABIL",
  REGISTRAR_PENDENCIA_MANUAL: "NUCLEO_CONTABIL",
  JUSTIFICAR_PENDENCIA: "NUCLEO_CONTABIL",
  SUBMETER_CAPTURA: "INTEGRACOES_E_PRESTACAO_DE_CONTAS",
  IMPORTAR_FOLHA: "INTEGRACOES_E_PRESTACAO_DE_CONTAS",
  IMPORTAR_TRIBUTOS: "TRIBUTOS_E_ARRECADACAO",
  CADASTRAR_CLASSE_DE_MATERIAL: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_ENTRADA_ALMOXARIFADO: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_SAIDA_CONSUMO: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_AJUSTE_ALMOXARIFADO: "PATRIMONIO_E_ALMOXARIFADO",
  ESTORNAR_MOVIMENTO_ALMOXARIFADO: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_DEPOSITO: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_UNIDADE_DE_MEDIDA: "PLATAFORMA",
  CADASTRAR_GRUPO_DE_MATERIAL: "PLATAFORMA",
  CADASTRAR_MATERIAL: "PLATAFORMA",
  DEFINIR_PARAMETRO_DE_ESTOQUE: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_ENTRADA_FISICA: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_SAIDA_FISICA: "PATRIMONIO_E_ALMOXARIFADO",
  ESTORNAR_MOVIMENTO_FISICO: "PATRIMONIO_E_ALMOXARIFADO",
  TRANSFERIR_ENTRE_DEPOSITOS: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_REQUISICAO_DE_MATERIAL: "PATRIMONIO_E_ALMOXARIFADO",
  DEFINIR_COTA_DE_CONSUMO: "PATRIMONIO_E_ALMOXARIFADO",
  ABRIR_INVENTARIO_DE_ESTOQUE: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_CONTAGEM_DE_INVENTARIO: "PATRIMONIO_E_ALMOXARIFADO",
  FECHAR_INVENTARIO_DE_ESTOQUE: "PATRIMONIO_E_ALMOXARIFADO",
  BLOQUEAR_ESTOQUE: "PATRIMONIO_E_ALMOXARIFADO",
  ENCERRAR_BLOQUEIO_DE_ESTOQUE: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_CLASSE_DE_BENS: "PLATAFORMA",
  CADASTRAR_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  PARAMETRIZAR_ROTEIRO_PATRIMONIAL: "PATRIMONIO_E_ALMOXARIFADO",
  PUBLICAR_ROTEIRO_PATRIMONIAL: "PATRIMONIO_E_ALMOXARIFADO",
  DEFINIR_PARAMETRO_DE_ATUALIZACAO: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_LOCALIZACAO_FISICA: "PLATAFORMA",
  CADASTRAR_COMISSAO_PATRIMONIAL: "PLATAFORMA",
  CADASTRAR_MOTIVO_DE_BAIXA: "PLATAFORMA",
  CADASTRAR_TIPO_DE_INCORPORACAO: "PLATAFORMA",
  CADASTRAR_FORMULA_DE_AVALIACAO: "PLATAFORMA",
  REGISTRAR_MOVIMENTO_DE_GESTAO: "PATRIMONIO_E_ALMOXARIFADO",
  TRANSFERIR_BEM_ENTRE_ENTIDADES: "PATRIMONIO_E_ALMOXARIFADO",
  ESTORNAR_MOVIMENTO_DE_GESTAO: "PATRIMONIO_E_ALMOXARIFADO",
  GERAR_ETIQUETA_DE_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  EMITIR_TERMO_PATRIMONIAL: "PATRIMONIO_E_ALMOXARIFADO",
  ABRIR_INVENTARIO_DE_BENS: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_CONTAGEM_DE_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  FECHAR_INVENTARIO_DE_BENS: "PATRIMONIO_E_ALMOXARIFADO",
  REPONTAR_CONTA: "NUCLEO_CONTABIL",
  RELACIONAR_MARCA_AO_MATERIAL: "PLATAFORMA",
  RELACIONAR_ELEMENTO_AO_MATERIAL: "PLATAFORMA",
  REGISTRAR_SOLICITACAO_DE_COMPRA: "COMPRAS_E_CONTRATOS",
  MOVIMENTAR_SOLICITACAO_DE_COMPRA: "COMPRAS_E_CONTRATOS",
  REGISTRAR_PESQUISA_DE_PRECOS: "COMPRAS_E_CONTRATOS",
  EMITIR_ORDEM_DE_COMPRA: "COMPRAS_E_CONTRATOS",
  REGISTRAR_RECEBIMENTO_DE_ORDEM: "COMPRAS_E_CONTRATOS",
  ESTORNAR_ORDEM_DE_COMPRA: "COMPRAS_E_CONTRATOS",
  REGISTRAR_DOCUMENTO_FISCAL: "COMPRAS_E_CONTRATOS",
  CONFERIR_DOCUMENTO_FISCAL: "COMPRAS_E_CONTRATOS",
  CANCELAR_DOCUMENTO_FISCAL: "COMPRAS_E_CONTRATOS",
  ADQUIRIR_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_ENTRADA_AVULSA: "PATRIMONIO_E_ALMOXARIFADO",
  ALIENAR_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  BAIXAR_BEM: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_REAVALIACAO: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_IMPAIRMENT: "PATRIMONIO_E_ALMOXARIFADO",
  REGISTRAR_CUSTO_SUBSEQUENTE: "PATRIMONIO_E_ALMOXARIFADO",
  ATUALIZAR_COMPETENCIA_PATRIMONIAL: "PATRIMONIO_E_ALMOXARIFADO",
  ESTORNAR_MOVIMENTO_PATRIMONIAL: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_DIVIDA: "NUCLEO_CONTABIL",
  REGISTRAR_ATUALIZACAO_MONETARIA: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_DIVIDA: "NUCLEO_CONTABIL",
  CADASTRAR_DIVIDA_ATIVA: "TRIBUTOS_E_ARRECADACAO",
  INSCREVER_DIVIDA_ATIVA: "TRIBUTOS_E_ARRECADACAO",
  ATUALIZAR_DIVIDA_ATIVA: "TRIBUTOS_E_ARRECADACAO",
  CANCELAR_DIVIDA_ATIVA: "TRIBUTOS_E_ARRECADACAO",
  ESTORNAR_MOVIMENTO_DIVIDA_ATIVA: "TRIBUTOS_E_ARRECADACAO",
  CADASTRAR_PROVISAO: "PATRIMONIO_E_ALMOXARIFADO",
  CONSTITUIR_PROVISAO: "PATRIMONIO_E_ALMOXARIFADO",
  REVERTER_PROVISAO: "PATRIMONIO_E_ALMOXARIFADO",
  ATUALIZAR_PROVISAO: "PATRIMONIO_E_ALMOXARIFADO",
  ESTORNAR_MOVIMENTO_PROVISAO: "PATRIMONIO_E_ALMOXARIFADO",
  CADASTRAR_PROCESSO: "COMPRAS_E_CONTRATOS",
  HOMOLOGAR_PROCESSO: "COMPRAS_E_CONTRATOS",
  CADASTRAR_CONTRATO: "COMPRAS_E_CONTRATOS",
  REGISTRAR_ADITIVO: "COMPRAS_E_CONTRATOS",
  ESTORNAR_MOVIMENTO_CONTRATUAL: "COMPRAS_E_CONTRATOS",
  CADASTRAR_LIMITE: "COMPRAS_E_CONTRATOS",
  CADASTRAR_OBRA: "COMPRAS_E_CONTRATOS",
  CADASTRAR_LINHA_DEMONSTRATIVO: "NUCLEO_CONTABIL",
  CADASTRAR_PESSOA: "PLATAFORMA",
  ALTERAR_PESSOA: "PLATAFORMA",
  MOVER_PAPEL_DE_PESSOA: "PLATAFORMA",
  TRAVAR_COMPETENCIA: "NUCLEO_CONTABIL",
  DESTRAVAR_COMPETENCIA: "NUCLEO_CONTABIL",
  CRIAR_USUARIO: "PLATAFORMA",
  CONCEDER_PERFIL: "PLATAFORMA",
  REVOGAR_PERFIL: "PLATAFORMA",
  ATIVAR_USUARIO: "PLATAFORMA",
  INATIVAR_USUARIO: "PLATAFORMA",
  RESETAR_SENHA: "PLATAFORMA",
  CRIAR_PERFIL: "PLATAFORMA",
  CONCEDER_ACAO_A_PERFIL: "PLATAFORMA",
  REVOGAR_ACAO_DE_PERFIL: "PLATAFORMA",
  VINCULAR_PESSOA_AO_USUARIO: "PLATAFORMA",
  CONFIGURAR_APRESENTACAO_DO_ENTE: "PLATAFORMA",
  ATRIBUIR_CONTA_A_ARRECADACAO: "NUCLEO_CONTABIL",
  // ── V11 V9 — a entidade contábil. As três no NÚCLEO CONTÁBIL, e não em TRIBUTOS: o que elas
  // decidem é de QUEM é o dinheiro que entrou (5.10.1.3 — contabilização distinta), e isso vale
  // para toda receita do ente, não só a tributária. Pô-las no módulo de tributos deixaria um ente
  // que não contratou tributos sem poder dizer quem são as suas entidades.
  CADASTRAR_ENTIDADE_CONTABIL: "NUCLEO_CONTABIL",
  DECLARAR_TITULAR_DA_CONTA_BANCARIA: "NUCLEO_CONTABIL",
  ATRIBUIR_ENTIDADE_A_ARRECADACAO: "NUCLEO_CONTABIL",
  CADASTRAR_SERVIDOR: "PESSOAL_E_FOLHA",
  ADMITIR_SERVIDOR: "PESSOAL_E_FOLHA",
  MOVIMENTAR_SERVIDOR: "PESSOAL_E_FOLHA",
  ALTERAR_REMUNERACAO: "PESSOAL_E_FOLHA",
  DESLIGAR_SERVIDOR: "PESSOAL_E_FOLHA",
  CADASTRAR_CARGO: "PESSOAL_E_FOLHA",
  CADASTRAR_LOTACAO: "PESSOAL_E_FOLHA",
  GERIR_DEPENDENTE: "PESSOAL_E_FOLHA",
  BAIXAR_DEPENDENTE: "PESSOAL_E_FOLHA",
  REGISTRAR_PORTARIA: "PESSOAL_E_FOLHA",
  REGISTRAR_ANOTACAO: "PESSOAL_E_FOLHA",
  REGISTRAR_TREINAMENTO: "PESSOAL_E_FOLHA",
  CONFIGURAR_CALENDARIO_RH: "PESSOAL_E_FOLHA",
  REGISTRAR_CONTRATO_TRABALHO: "PESSOAL_E_FOLHA",
  REGISTRAR_AVALIACAO_EXPERIENCIA: "PESSOAL_E_FOLHA",
  CONFIGURAR_TABELAS_DA_FOLHA: "PESSOAL_E_FOLHA",
  // V11 V9.1 — o 13º é folha: mesmo módulo comercial das demais ações do M33.
  CONFIGURAR_PARAMETRO_DO_DECIMO_TERCEIRO: "PESSOAL_E_FOLHA",
  CONFIGURAR_PARAMETRO_DO_ADIANTAMENTO_SALARIAL: "PESSOAL_E_FOLHA",
  CADASTRAR_GRUPO_DE_EMPENHO_DA_FOLHA: "PESSOAL_E_FOLHA",
  APROPRIAR_FOLHA: "PESSOAL_E_FOLHA",
  DESIGNAR_NA_FOLHA: "PESSOAL_E_FOLHA",
  CERTIFICAR_FOLHA: "PESSOAL_E_FOLHA",
  LIQUIDAR_FOLHA: "PESSOAL_E_FOLHA",
  CADASTRAR_ENCARGO_DA_FOLHA: "PESSOAL_E_FOLHA",
  APROVAR_ENCARGO_DA_FOLHA: "PESSOAL_E_FOLHA",
  APURAR_ENCARGOS_DA_FOLHA: "PESSOAL_E_FOLHA",
  CERTIFICAR_ENCARGOS_DA_FOLHA: "PESSOAL_E_FOLHA",
  GERIR_GUIA_DE_RECOLHIMENTO: "PESSOAL_E_FOLHA",
  TRIAR_MANIFESTACAO_DE_OUVIDORIA: "ATENDIMENTO_AO_CIDADAO",
  MODERAR_AVALIACAO_DE_SERVICO: "ATENDIMENTO_AO_CIDADAO",
  DESIGNAR_NO_CONTRATO: "COMPRAS_E_CONTRATOS",
  DEFINIR_ADMINISTRADOR_DA_FISCALIZACAO: "COMPRAS_E_CONTRATOS",
  CONFIGURAR_EXECUCAO_DO_CONTRATO: "COMPRAS_E_CONTRATOS",
  EMITIR_ORDEM_DE_SERVICO_DO_CONTRATO: "COMPRAS_E_CONTRATOS",
  GERIR_PLANILHA_DA_OBRA: "COMPRAS_E_CONTRATOS",
  GERIR_TIPOS_DE_OCORRENCIA: "COMPRAS_E_CONTRATOS",
  GERIR_CADASTRO_IMOBILIARIO: "TRIBUTOS_E_ARRECADACAO",
  GERIR_PARAMETROS_TRIBUTARIOS: "TRIBUTOS_E_ARRECADACAO",
  REGISTRAR_RECEBIMENTO_PROVISORIO: "COMPRAS_E_CONTRATOS",
  REGISTRAR_RECEBIMENTO_DEFINITIVO: "COMPRAS_E_CONTRATOS",
  ESTORNAR_RECEBIMENTO_DEFINITIVO: "COMPRAS_E_CONTRATOS",
  CADASTRAR_ITEM_DO_CONTRATO: "COMPRAS_E_CONTRATOS",
  PROGRAMAR_FISCALIZACAO_DO_CONTRATO: "COMPRAS_E_CONTRATOS",
  REGISTRAR_OCORRENCIA_DE_FISCALIZACAO: "COMPRAS_E_CONTRATOS",
  RESOLVER_OCORRENCIA_DE_FISCALIZACAO: "COMPRAS_E_CONTRATOS",
  CONFIGURAR_CARTA_DE_SERVICOS: "ATENDIMENTO_AO_CIDADAO",
  DECIDIR_SOLICITACAO_DE_SERVICO: "ATENDIMENTO_AO_CIDADAO",
  SOLICITAR_SERVICO: "ATENDIMENTO_AO_CIDADAO",
  REGISTRAR_REPRESENTACAO: "PLATAFORMA",
  // M07 V11 V8.3 — a consignação é do núcleo contábil: ela decide onde o passivo nasce.
  GERIR_TIPOS_DE_CONSIGNACAO: "NUCLEO_CONTABIL",
  PARAMETRIZAR_ROTEIRO_ORCAMENTARIO: "NUCLEO_CONTABIL",
  PARAMETRIZAR_ROTEIRO_RESTOS_A_PAGAR: "NUCLEO_CONTABIL",
  DISTRIBUIR_RECEITA_FORA_DA_PREVISAO: "NUCLEO_CONTABIL",
  GERIR_ROL_DE_FONTES_DA_CONTA: "NUCLEO_CONTABIL",
  // M21 V11 V8 — a agenda do guichê é atendimento ao cidadão, como a carta de serviços.
  CONFIGURAR_AGENDA_DO_GUICHE: "ATENDIMENTO_AO_CIDADAO",
  RESERVAR_ATENDIMENTO_NO_GUICHE: "ATENDIMENTO_AO_CIDADAO",
  REGISTRAR_ATENDIMENTO_NO_GUICHE: "ATENDIMENTO_AO_CIDADAO",
  CADASTRAR_RUBRICA: "PESSOAL_E_FOLHA",
  CADASTRAR_VERSAO_DE_RUBRICA: "PESSOAL_E_FOLHA",
  APROVAR_VERSAO_DE_RUBRICA: "PESSOAL_E_FOLHA",
  REVOGAR_VERSAO_DE_RUBRICA: "PESSOAL_E_FOLHA",
  LANCAR_NA_FOLHA: "PESSOAL_E_FOLHA",
  ABRIR_FOLHA: "PESSOAL_E_FOLHA",
  CALCULAR_FOLHA: "PESSOAL_E_FOLHA",
  SELECIONAR_VINCULOS_DA_FOLHA: "PESSOAL_E_FOLHA",
  CANCELAR_CALCULO_DA_FOLHA: "PESSOAL_E_FOLHA",
  FECHAR_FOLHA: "PESSOAL_E_FOLHA",
  ABRIR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  TRAMITAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  RECEBER_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  COMPLEMENTAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  SOLICITAR_PARECER: "ATENDIMENTO_AO_CIDADAO",
  RESPONDER_PARECER: "ATENDIMENTO_AO_CIDADAO",
  SOLICITAR_READEQUACAO: "ATENDIMENTO_AO_CIDADAO",
  ATENDER_READEQUACAO: "ATENDIMENTO_AO_CIDADAO",
  ENCERRAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  ARQUIVAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  REABRIR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  APENSAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  DESAPENSAR_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  TORNAR_MOVIMENTO_SEM_EFEITO: "ATENDIMENTO_AO_CIDADAO",
  CRIAR_SETOR: "ATENDIMENTO_AO_CIDADAO",
  LOTAR_USUARIO_NO_SETOR: "ATENDIMENTO_AO_CIDADAO",
  CRIAR_ASSUNTO: "ATENDIMENTO_AO_CIDADAO",
  PUBLICAR_CONFIGURACAO_DO_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  PROTOCOLAR_PEDIDO_DE_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  DISTRIBUIR_PEDIDO_DE_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  PRORROGAR_PEDIDO_DE_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  RESPONDER_PEDIDO_DE_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  DECIDIR_RECURSO_DE_ACESSO_A_INFORMACAO: "ATENDIMENTO_AO_CIDADAO",
  REGISTRAR_TAXA_DO_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  BAIXAR_TAXA_DO_PROCESSO: "ATENDIMENTO_AO_CIDADAO",
  ANEXAR_ARQUIVO: "PLATAFORMA",
  ASSINAR_DOCUMENTO: "PLATAFORMA",
  CRIAR_FILA_DE_ASSINATURA: "PLATAFORMA",
  ASSINAR_NA_FILA: "PLATAFORMA",
  CRIAR_TIPO_DE_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  RASCUNHAR_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  EDITAR_RASCUNHO_DE_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  ENVIAR_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  RESPONDER_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  ENCAMINHAR_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  MARCAR_LEITURA_DE_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  GERIR_MINHA_CAIXA: "ATENDIMENTO_AO_CIDADAO",
  ETIQUETAR_COMUNICADO: "ATENDIMENTO_AO_CIDADAO",
  DEFINIR_CAMPO_ADICIONAL: "PLATAFORMA",
  DESATIVAR_CAMPO_ADICIONAL: "PLATAFORMA",
  PREENCHER_CAMPOS_ADICIONAIS: "PLATAFORMA",
  CRIAR_MODELO_DE_RELATORIO: "NUCLEO_CONTABIL",
  NOVA_VERSAO_DE_MODELO: "NUCLEO_CONTABIL",
  COPIAR_MODELO_DE_RELATORIO: "NUCLEO_CONTABIL",
  DISTRIBUIR_MODELO_DE_RELATORIO: "NUCLEO_CONTABIL",
  RETIRAR_MODELO_DE_RELATORIO: "NUCLEO_CONTABIL",
  EXECUTAR_RELATORIO: "NUCLEO_CONTABIL",
  ESCREVER_AJUDA_DE_ROTA: "PLATAFORMA",
  CRIAR_NIVEL_DE_SEVERIDADE: "PLATAFORMA",
  ABRIR_CHAMADO: "PLATAFORMA",
  RESPONDER_CHAMADO: "PLATAFORMA",
  ENCERRAR_CHAMADO: "PLATAFORMA",
  REABRIR_CHAMADO: "PLATAFORMA",
  RESPONDER_PESQUISA_DE_SATISFACAO: "PLATAFORMA",
  CRIAR_LOTE_DE_PAGAMENTO: "NUCLEO_CONTABIL",
  INCLUIR_NO_LOTE: "NUCLEO_CONTABIL",
  FECHAR_LOTE: "NUCLEO_CONTABIL",
  GERAR_BORDERO: "NUCLEO_CONTABIL",
  PROCESSAR_RETORNO_BANCARIO: "NUCLEO_CONTABIL",
  CADASTRAR_CONVENIO: "NUCLEO_CONTABIL",
  LIBERAR_PARCELA_DE_CONVENIO: "NUCLEO_CONTABIL",
  APROVAR_PRESTACAO_DE_CONTAS: "NUCLEO_CONTABIL",
  GLOSAR_CONVENIO: "NUCLEO_CONTABIL",
  REGISTRAR_DEVOLUCAO_DE_CONVENIO: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_DE_CONVENIO: "NUCLEO_CONTABIL",
  CADASTRAR_PRECATORIO: "NUCLEO_CONTABIL",
  INSCREVER_PRECATORIO: "NUCLEO_CONTABIL",
  ATUALIZAR_PRECATORIO: "NUCLEO_CONTABIL",
  CANCELAR_PRECATORIO: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_DE_PRECATORIO: "NUCLEO_CONTABIL",
  CADASTRAR_CONSORCIO: "NUCLEO_CONTABIL",
  REGISTRAR_CONTRATO_DE_RATEIO: "NUCLEO_CONTABIL",
  REPASSAR_AO_CONSORCIO: "NUCLEO_CONTABIL",
  REGISTRAR_DEVOLUCAO_DE_CONSORCIO: "NUCLEO_CONTABIL",
  ESTORNAR_MOVIMENTO_DE_CONSORCIO: "NUCLEO_CONTABIL",
  REGISTRAR_MEDICAO_DE_OBRA: "COMPRAS_E_CONTRATOS",
  APROVAR_MEDICAO_DE_OBRA: "COMPRAS_E_CONTRATOS",
  ABRIR_AUDITORIA_INTERNA: "TRANSPARENCIA_E_CONTROLE",
  RESPONDER_CHECKLIST_DE_AUDITORIA: "TRANSPARENCIA_E_CONTROLE",
  REGISTRAR_IRREGULARIDADE: "TRANSPARENCIA_E_CONTROLE",
  REGISTRAR_PROVIDENCIA: "TRANSPARENCIA_E_CONTROLE",
  APRECIAR_PROVIDENCIA: "TRANSPARENCIA_E_CONTROLE",
  ENCERRAR_AUDITORIA_INTERNA: "TRANSPARENCIA_E_CONTROLE",
  EMITIR_RELATORIO_CIRCUNSTANCIADO: "TRANSPARENCIA_E_CONTROLE",
  CONSULTAR_PLANEJAMENTO: "NUCLEO_CONTABIL",
  CONSULTAR_RECEITA: "NUCLEO_CONTABIL",
  CONSULTAR_DESPESA: "NUCLEO_CONTABIL",
  CONSULTAR_FINANCEIRO: "NUCLEO_CONTABIL",
  CONSULTAR_PATRIMONIO: "PATRIMONIO_E_ALMOXARIFADO",
  CONSULTAR_LICITACOES: "COMPRAS_E_CONTRATOS",
  CONSULTAR_CONTABILIDADE: "NUCLEO_CONTABIL",
  CONSULTAR_RELATORIOS: "NUCLEO_CONTABIL",
  CONSULTAR_TRANSPARENCIA: "TRANSPARENCIA_E_CONTROLE",
  CADASTRAR_POLITICA_DE_PESSOAL: "TRANSPARENCIA_E_CONTROLE",
  APROVAR_POLITICA_DE_PESSOAL: "TRANSPARENCIA_E_CONTROLE",
  REVOGAR_POLITICA_DE_PESSOAL: "TRANSPARENCIA_E_CONTROLE",
  CONSULTAR_PROTOCOLO: "ATENDIMENTO_AO_CIDADAO",
  CONSULTAR_COMUNICACAO: "ATENDIMENTO_AO_CIDADAO",
  CONSULTAR_CADASTROS: "PLATAFORMA",
  CONSULTAR_TRANSFERENCIAS: "NUCLEO_CONTABIL",
  CONSULTAR_DIVIDA: "NUCLEO_CONTABIL",
  CONSULTAR_CONTROLE_INTERNO: "TRANSPARENCIA_E_CONTROLE",
  CONSULTAR_ADMINISTRACAO: "PLATAFORMA",
  CONSULTAR_INTEGRACOES: "INTEGRACOES_E_PRESTACAO_DE_CONTAS",
  CONSULTAR_SUPORTE: "PLATAFORMA",
  CONSULTAR_PESSOAL: "PESSOAL_E_FOLHA",
  CONSULTAR_FOLHA: "PESSOAL_E_FOLHA",
  CONSULTAR_PORTAL_DO_SERVIDOR: "PESSOAL_E_FOLHA",
  CONSULTAR_MEUS_SERVICOS: "ATENDIMENTO_AO_CIDADAO",
  // ⚠️ O PRÓPRIO LICENCIAMENTO É PLATAFORMA, e tinha de ser: se ele fosse licenciável, uma
  // suspensão trancaria a tela que a desfaz, e a saída seria mexer no banco à mão.
  REGISTRAR_CONTRATO_COMERCIAL: "PLATAFORMA",
  ENCERRAR_CONTRATO_COMERCIAL: "PLATAFORMA",
  HABILITAR_MODULO_CONTRATADO: "PLATAFORMA",
  PROGRAMAR_VIGENCIA_DE_MODULO: "PLATAFORMA",
  SUSPENDER_MODULO_CONTRATADO: "PLATAFORMA",
  REATIVAR_MODULO_CONTRATADO: "PLATAFORMA",
  CONSULTAR_LICENCIAMENTO: "PLATAFORMA",
  // V10 T2 — o lançamento tributário e a certidão são do módulo de TRIBUTOS, e não do núcleo:
  // um ente que contratou só a contabilidade não lança IPTU.
  PREPARAR_LANCAMENTO_TRIBUTARIO: "TRIBUTOS_E_ARRECADACAO",
  CONSTITUIR_CREDITO_TRIBUTARIO: "TRIBUTOS_E_ARRECADACAO",
  RETIFICAR_LANCAMENTO_TRIBUTARIO: "TRIBUTOS_E_ARRECADACAO",
  CANCELAR_LANCAMENTO_TRIBUTARIO: "TRIBUTOS_E_ARRECADACAO",
  SOLICITAR_CERTIDAO: "TRIBUTOS_E_ARRECADACAO",
  DECIDIR_CERTIDAO: "TRIBUTOS_E_ARRECADACAO",
  DEFINIR_DIVULGACAO_DA_LOCALIZACAO: "PATRIMONIO_E_ALMOXARIFADO",
};
