export * from './faixas-progressivas.js'
export * from './proporcionalidade.js'
export * from './inss.js'
export * from './irrf.js'
export * from './salario-familia.js'
export * from './decimo-terceiro.js'
