-- V7 M2 U1 — a ação da ordem de serviço do contrato. SEPARADA das tabelas.
ALTER TYPE "AcaoDoSistema" ADD VALUE 'EMITIR_ORDEM_DE_SERVICO_DO_CONTRATO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_RECEBIMENTO_PROVISORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_RECEBIMENTO_DEFINITIVO';
