-- V6 P2.3 — M33 FOLHA DE PAGAMENTO (RH bloco 2): sete ações e a leitura da área.
-- SEPARADA das tabelas: ALTER TYPE ADD VALUE não convive com o uso do valor na mesma transação.
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONFIGURAR_TABELAS_DA_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_RUBRICA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'LANCAR_NA_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ABRIR_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CALCULAR_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CANCELAR_CALCULO_DA_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'FECHAR_FOLHA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_FOLHA';
