-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_CONVENIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'LIBERAR_PARCELA_DE_CONVENIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'APROVAR_PRESTACAO_DE_CONTAS';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'GLOSAR_CONVENIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_DEVOLUCAO_DE_CONVENIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ESTORNAR_MOVIMENTO_DE_CONVENIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_PRECATORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'INSCREVER_PRECATORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ATUALIZAR_PRECATORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CANCELAR_PRECATORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ESTORNAR_MOVIMENTO_DE_PRECATORIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_CONSORCIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_CONTRATO_DE_RATEIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REPASSAR_AO_CONSORCIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ESTORNAR_MOVIMENTO_DE_CONSORCIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_MEDICAO_DE_OBRA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'APROVAR_MEDICAO_DE_OBRA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ABRIR_AUDITORIA_INTERNA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'RESPONDER_CHECKLIST_DE_AUDITORIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_IRREGULARIDADE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_PROVIDENCIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'APRECIAR_PROVIDENCIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ENCERRAR_AUDITORIA_INTERNA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'EMITIR_RELATORIO_CIRCUNSTANCIADO';
