-- V6 P2 — M32 PESSOAL (RH bloco 1, conciliado do siafic-cg c04ad5a): catorze ações e a leitura da área.
-- SEPARADA das tabelas: ALTER TYPE ADD VALUE não convive com o uso do valor na mesma transação.
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_SERVIDOR';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ADMITIR_SERVIDOR';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'MOVIMENTAR_SERVIDOR';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ALTERAR_REMUNERACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'DESLIGAR_SERVIDOR';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_CARGO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_LOTACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'GERIR_DEPENDENTE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'BAIXAR_DEPENDENTE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_PORTARIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_ANOTACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_TREINAMENTO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONFIGURAR_CALENDARIO_RH';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_CONTRATO_TRABALHO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_AVALIACAO_EXPERIENCIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_PESSOAL';
