-- V7 M2.1 — as ações do contrato acompanhado. SEPARADA das tabelas (ALTER TYPE ADD VALUE).
ALTER TYPE "AcaoDoSistema" ADD VALUE 'DESIGNAR_NO_CONTRATO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_ITEM_DO_CONTRATO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'PROGRAMAR_FISCALIZACAO_DO_CONTRATO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_OCORRENCIA_DE_FISCALIZACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'RESOLVER_OCORRENCIA_DE_FISCALIZACAO';
