/**
 * V36 — LEVANTAMENTO DAS CLÁUSULAS DE CONTABILIDADE (5.9 e 5.10) QUE ESTAVAM NAO_VERIFICADO.
 *
 * 2026-10-05, sobre o commit 9020303e (V35 publicada como 8b63c84). Sete varreduras somente
 * leitura, uma por fatia, cláusula por cláusula contra o código, os testes e os percursos.
 * Cada marca diz o que existe, o que falta, e — quando o sistema faz a mesma coisa por
 * outro caminho (estorno no lugar de alteração, efetivação no lugar de "disponibilizar",
 * cota por fonte no lugar de contingenciamento por percentual) — diz qual caminho e se o
 * efeito é o mesmo. Diferença de nome não rebaixa; diferença de efeito rebaixa.
 *
 * Na dúvida, o nível mais baixo. Onde o percurso que sustentaria a validação está
 * desatualizado (o de adiantamentos é anterior à guarda da devolução da V35), a marca fica
 * em IMPLEMENTADO_NAO_VALIDADO até o percurso rodar de novo.
 */
type Situacao =
  | "NAO_VERIFICADO"
  | "AUSENTE_CONFIRMADO"
  | "PARCIAL"
  | "IMPLEMENTADO_NAO_VALIDADO"
  | "VALIDADO_LOCALMENTE"
  | "DEPENDENCIA_EXTERNA";

interface Marca {
  readonly situacao: Situacao;
  readonly evidencia: string;
  readonly rota_verificada?: string;
}

const V36 = "V36 (levantamento 2026-10-05, commit 9020303e):";

const ROTA_ADIANTAMENTOS =
  "papel: administrador (EMPENHAR) · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-05 · passos: /despesa/adiantamentos → conceder diária (destino, 2,5 x 200,00) → controle 7/8 conferido no banco → /transparencia/diarias mostra a diária com CPF mascarado → conceder suprimento → prestação com 50,00 devolvidos → aprovar é recusado com o motivo e nada é gravado → rejeitar com parecer → nova prestação sem devolução → aprovar → a baixa inverte o controle da concessão → prestação da diária aprovada → recarga mostra as duas comprovadas · obtido: 19/19 · artefato: scripts/percurso-v36-adiantamentos.mts.";

function m(situacao: Situacao, evidencia: string, rota?: string): Marca {
  return rota === undefined
    ? { situacao, evidencia: `${V36} ${evidencia}` }
    : { situacao, evidencia: `${V36} ${evidencia}`, rota_verificada: rota };
}

export const MARCAS_V36: Readonly<Record<string, Marca>> = {
  // ═══ 5.9.1 PPA ═══
  "5.9.1.1": m("AUSENTE_CONFIRMADO", "não há cadastro de audiência pública (schema, módulos, telas). modules/m02b-plurianual/MODULO.md e docs/varreduras/varredura-v18-versao-do-planejamento.md registram como outro domínio; o M21 trata pedido de acesso, não audiência. FALTA: AudienciaPublica com as solicitações da comunidade (bairro, contato, órgão analisador, status)."),
  "5.9.1.2": m("AUSENTE_CONFIRMADO", "sem a audiência (5.9.1.1) não há a que anexar. O anexo do M22 existe e funciona (leis orçamentárias usam ANEXAR_ARQUIVO), mas cada dono é uma FK própria em Anexo. FALTA: o dono audiência e a aba de anexos."),
  "5.9.1.4": m("PARCIAL", "a estrutura do PPA (EixoEstruturante, AreaTematica, PublicoAlvo, Macroacao, função e subfunção em AcaoPpa — prisma/schema/m02b-plurianual.prisma) é cadastrada em /planejamento/ppa/estrutura, com m02b-plurianual.test.ts e scripts/smoke-plurianual.ts. É cadastro livre do ente. FALTA: a tabela de vínculos do TCE como domínio oficial — depende de transcrição de fonte oficial.", "papel: CADASTRAR_PPA · /planejamento/ppa/estrutura · percurso scripts/smoke-plurianual.ts."),
  "5.9.1.8": m("AUSENTE_CONFIRMADO", "não há geração de código reduzido. FichaOrcamentaria.numero é único no exercício mas digitado (lib/portas/recursos/fichas.ts), não composto da classificação; o PPA não tem classificação completa da despesa. FALTA: o código reduzido gerado automaticamente."),
  "5.9.1.12": m("PARCIAL", "PrevisaoReceitaPpa guarda a previsão por natureza, fonte e ano do quadriênio, com tela /planejamento/ppa/[id] e scripts/smoke-plurianual.ts. FALTA: o rateio automático por percentual de fonte — cada linha natureza x fonte x ano é digitada em valor absoluto; não há tabela de repartição.", "/planejamento/ppa/[id] · scripts/smoke-plurianual.ts."),
  "5.9.1.17": m("AUSENTE_CONFIRMADO", "não há previsão de transferência financeira no PPA nem na LOA. TransferenciaEntreUgs é o fato realizado, lançado no razão, não a previsão. FALTA: previsão por ano do PPA com a entidade de destino."),
  "5.9.1.19": m("PARCIAL", "o planejamento é ato do ente (o MODULO do M02b recusa unidade nas tabelas do PPA e LDO); a despesa da LOA tem recorte consolidado ou por unidade no QDD (/planejamento/qdd) e as alterações saem pelos créditos adicionais (smoke-credito-adicional.ts). FALTA: dimensão de entidade na receita prevista e no PPA, previsão de transferência, e seleção de duas ou mais entidades para somar.", "/planejamento/qdd · scripts/smoke-credito-adicional.ts."),
  "5.9.1.20": m("AUSENTE_CONFIRMADO", "no PPA a despesa não tem fonte (AcaoPpa só metaFinanceira), logo não há confronto por fonte. O equivalente existe só para a LOA (modules/m12-relatorios/consistencia-loa.ts, POR_FONTE, m12-consistencia-loa.test.ts), sobre a previsão inicial. FALTA: fonte na despesa do PPA, o confronto, o corte por data e a consolidação."),
  "5.9.1.24": m("PARCIAL", "PPA só tem telas de lista e detalhe, sem relatório emissível; a LOA emite PDF e Excel por anexo (/planejamento/loa/pdf, /xlsx). FALTA: relatório gerencial do PPA por fonte, de transferências, e seleção de entidades.", "/planejamento/ppa/[id], /planejamento/loa · scripts/smoke-plurianual.ts."),
  "5.9.1.27": m("PARCIAL", "dos onze relatórios, há telas equivalentes para programas detalhados (/planejamento/ppa/programas e /[id]) e para a receita por ano (aba histórico do plano); o corte 'situação até' existe só em /planejamento/alteracoes (m02b-alteracao.test.ts, smoke-alteracoes-do-planejamento.ts). FALTA: os demais relatórios nomeados, a saída impressa e a consolidação de entidades.", "/planejamento/ppa/programas · scripts/smoke-plurianual.ts."),
  "5.9.1.28": m("AUSENTE_CONFIRMADO", "a pendência VINCULO-PPA-LOA (modules/m02b-plurianual/MODULO.md) registra que a ficha não se liga à ação do PPA; a LOA não emite o quadro de compatibilidade com as metas da LDO. FALTA: o vínculo e os dois relatórios de compatibilização — depende da decisão do grão do vínculo."),
  "5.9.1.31": m("IMPLEMENTADO_NAO_VALIDADO", "os demonstrativos existem: RREO Anexo 3 (RCL), Anexo 8 (MDE), Anexo 12 (saúde) e RGF Anexo 1 (pessoal), em modules/m12-relatorios/rreo-anexo3.ts, rreo-anexo8.ts, rreo-anexo12.ts, rgf-anexo1.ts, cada um com teste m12-*.test.ts e tela em /relatorios/rreo e /relatorios/rgf. FALTA: percurso de navegador que confira os percentuais na tela — os conferidores só abrem as rotas."),
  "5.9.1.32": m("PARCIAL", "receita orçada e atualizada do PPA por linha de PrevisaoReceitaPpa, com corte por data, em /planejamento/alteracoes (m02b-alteracao.test.ts; smoke-alteracoes-do-planejamento.ts). FALTA: relatório emissível da receita do PPA, o grau da natureza (5.9.1.3) e a seleção por entidade.", "/planejamento/alteracoes · scripts/smoke-alteracoes-do-planejamento.ts."),

  // ═══ 5.9.2 LDO ═══
  "5.9.2.2": m("AUSENTE_CONFIRMADO", "a LDO tem trâmite, prioridades, metas anuais e anexos da LRF; não há vínculo com tabela do tribunal. FALTA: a tabela do TCE, que precisa ser transcrita de fonte oficial."),
  "5.9.2.9": m("AUSENTE_CONFIRMADO", "a LDO não tem previsão de receita, despesa ou transferência (pendência LDO-SEM-PREVISAO-ORCAMENTARIA no MODULO do M02b). Sem previsão, não há o que consolidar por entidade."),
  "5.9.2.14": m("AUSENTE_CONFIRMADO", "sem receita e despesa orçadas na LDO não há confronto por fonte. O equivalente existe só na LOA (consistencia-loa.ts, POR_FONTE). FALTA: as previsões da LDO e o confronto."),
  "5.9.2.15": m("AUSENTE_CONFIRMADO", "a LDO não tem receita, despesa nem programa de trabalho valorados; o anexo de prioridades (anexos/ldo.ts, m02b-anexos-ldo.test.ts) não é demonstrativo de receitas, de despesas nem programa de trabalho com valor. FALTA: os três relatórios."),
  "5.9.2.16": m("AUSENTE_CONFIRMADO", "não há cadastro de obras previstas na LDO. Obra (prisma/schema/m11-licitacoes.prisma) é cadastro de contratação, sem início, valor previsto, conservação nem novos projetos. FALTA: o cadastro."),
  "5.9.2.17": m("AUSENTE_CONFIRMADO", "o demonstrativo de obras e conservação do patrimônio não está entre os oito anexos de modules/m02b-plurianual/anexos/ldo.ts, e falta o cadastro que o alimentaria (5.9.2.16)."),
  "5.9.2.19": m("PARCIAL", "consistencia-loa.ts verifica sobre a previsão da LOA MDE >= 25% e Saúde >= 15% da base de impostos (m12-consistencia-loa.test.ts, tela /relatorios/consistencia); pessoal contra a RCL e FUNDEB 70% saem SEM_DADO. FALTA: os três demonstrativos sobre valores orçados como relatório, e tudo sobre a LDO, que não tem valores."),

  // ═══ 5.9.3 LOA ═══
  "5.9.3.4": m("AUSENTE_CONFIRMADO", "NaturezaReceita não tem relação com fonte; o vínculo nasce em cada ReceitaPrevista, com valor absoluto e sem percentual. FALTA: lista de fontes por natureza com percentual e soma <= 100%."),
  "5.9.3.5": m("PARCIAL", "a despesa tem tela e percurso: /planejamento/fichas cria ficha com função, subfunção, programa, ação, natureza, fonte e exercício da fonte (test/ficha-pela-tela.test.ts; scripts/smoke-ficha-pela-tela.ts). A receita prevista com fonte é criada por criarReceitaPrevista (modules/m02-planejamento/servico.ts), só pela carga da LOA e pela proposta. FALTA: tela para cadastrar a previsão de receita com fonte.", "/planejamento/fichas · scripts/smoke-ficha-pela-tela.ts."),
  "5.9.3.6": m("PARCIAL", "modules/m02-planejamento/proposta-orcamentaria.ts importa receitas e fichas do exercício de origem com base e percentual escolhidos (m02-proposta-orcamentaria.test.ts; smoke-proposta-orcamentaria.ts, percurso-v31-contador.ts); a base da despesa pode ser dotação inicial, autorizada ou empenhada. FALTA: importar da LDO (que não tem valores), base liquidado ou pago na despesa e arrecadado na receita.", "/planejamento/proposta-orcamentaria · scripts/smoke-proposta-orcamentaria.ts, scripts/percurso-v31-contador.ts."),
  "5.9.3.7": m("AUSENTE_CONFIRMADO", "não há rateio automático da receita da LOA por percentual de fonte; o valor é informado por linha natureza x fonte. FALTA: o cadastro de 5.9.3.4 e a divisão do valor."),
  "5.9.3.8": m("PARCIAL", "a atualização da receita é a reprevisão, append-only e com sinal (ReceitaReprevista; prevista atualizada = inicial + ajustes), com exercício, natureza, fonte, tipo da receita, valor, motivo e data; tela /planejamento/reprevisao com FormReprevisao.tsx; m02-reprevisao.test.ts. FALTA: tipo da atualização, ato e texto jurídico, data escolhida pelo usuário, e percurso de navegador."),
  "5.9.3.10": m("IMPLEMENTADO_NAO_VALIDADO", "modo diferente, mesmo efeito: a reprevisão não tem rascunho nem finalização — ao ser registrada, reprevisar (modules/m02-planejamento/adapter-prisma.ts) grava e lança no razão na mesma transação (lancarReprevisaoDaReceita): aumento em previsão adicional, redução em anulação, dedução na conta do seu tipo (V35). Testes t-razão e t-dedução em m02-reprevisao.test.ts. FALTA: percurso de navegador que registre pela tela e confira o razão."),
  "5.9.3.11": m("PARCIAL", "/planejamento/qdd mostra dotação inicial, créditos e atualizada por ficha, consolidada ou por unidade (smoke-credito-adicional.ts); /planejamento/comparacao-de-exercicios traz previsão atualizada e dotação autorizada. FALTA: corte 'até a data' na receita (reprevisaoAcumuladaPorNatureza só recebe o exercício) e na despesa, e seleção de entidades.", "/planejamento/qdd · scripts/smoke-credito-adicional.ts."),
  "5.9.3.12": m("PARCIAL", "a ficha tem elemento, destinação (fonte e exercício da fonte) e unidade orçamentária, com tela e percurso (/planejamento/fichas; smoke-ficha-pela-tela.ts; test/ficha-pela-tela.test.ts); totais por unidade e consolidado no QDD. FALTA: o valor pela tela — a ficha nasce com dotação zero por decisão (sem lei não há saldo); o valor entra pela carga da LOA (sem tela, pendência CARGA-DA-LOA-PELA-TELA) ou pela efetivação da proposta.", "/planejamento/fichas · scripts/smoke-ficha-pela-tela.ts."),
  "5.9.3.16": m("IMPLEMENTADO_NAO_VALIDADO", "o decreto de crédito (modules/m03-creditos/servico.ts) aceita N movimentos de suplementação e anulação em fichas e fontes diferentes, vários decretos consomem a mesma lei até o teto (m03.test.ts, m03-limite-da-loa.test.ts); a tela /planejamento/creditos-adicionais tem adicionar e remover movimento. FALTA: o percurso (smoke-credito-adicional.ts) grava só um movimento suplementar — multi-dotação e multi-fonte pela tela não foram exercidos."),
  "5.9.3.17": m("PARCIAL", "a ficha mostra o histórico dos movimentos de dotação, inclusive crédito, por competência (/planejamento/fichas/[id]); /relatorios/atualizacoes-orcamentarias lista os movimentos de crédito. FALTA: o relatório ordena por número do decreto, não por data, e o histórico da ficha não tem teste dedicado."),
  "5.9.3.18": m("PARCIAL", "a LOA sai consolidada e por unidade orçamentária (consultas-loa.ts, /planejamento/loa); a escrita é recortada por UG. FALTA: entidade como dimensão da previsão de receita e do razão, e seleção de duas ou mais entidades para consolidar receita, despesa, transferência e alteração."),
  "5.9.3.19": m("VALIDADO_LOCALMENTE", "modo diferente, mesmo efeito: 'disponibilizar' é a efetivação da proposta (proposta-orcamentaria.ts), que cria receita prevista e fichas do exercício de destino numa transação, com dotação inicial e previsão da receita no razão. Testes em m02-proposta-orcamentaria.test.ts (efetiva; recusa efetivar duas vezes e em exercício fechado). Ressalva: a efetivação não exige a lei aprovada registrada.", "papel: contador · /planejamento/proposta-orcamentaria · percurso scripts/percurso-v31-contador.ts C.5, C.6 e D.1 (abre 2027, gera o orçamento, confere a fase)."),
  "5.9.3.21": m("PARCIAL", "meta de arrecadação versionada por ato, por fonte e por bimestre (CotaCmd/MBA, registrarVersaoMba, proporMbaDaLoa em modules/m02-planejamento/programacao.ts), tela /planejamento/cmd-mba e confronto com o arrecadado (m02-programacao.test.ts t8). FALTA: grão mensal (o modelo é bimestral), modalidade, entidade, e tela de digitação manual.", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts."),
  "5.9.3.22": m("PARCIAL", "a ficha tem número inteiro único por exercício, que faz o papel de código reduzido da despesa (prisma/schema/m02-planejamento.prisma). FALTA: código reduzido na receita prevista e rotina de reordenar os números antes da execução."),
  "5.9.3.23": m("AUSENTE_CONFIRMADO", "não há prévia de alteração orçamentária: o decreto grava direto o movimento na dotação; rascunho.ts da tela de créditos é só validação de forma. FALTA: lote de prévias, aprovação, efetivação sem redigitação e impressão de projeto de lei."),
  "5.9.3.24": m("AUSENTE_CONFIRMADO", "sem prévia (5.9.3.23) não há bloqueio da dotação a anular nem desbloqueio na efetivação; ReservaDotacao do M05 existe mas não se liga a alteração orçamentária."),
  "5.9.3.25": m("PARCIAL", "modules/m02-planejamento/conferencia-da-proposta.ts confere a proposta da LOA: equilíbrio, despesa por fonte sem lastro, linhas negativas, metas e prioridades da LDO, ações contra o PPA, deduções sem tipo (m02-conferencia-da-proposta.test.ts k1 a k9; tela Conferencia.tsx; percurso-v31-contador.ts C.2 a C.4). FALTA: consistência interna do PPA e da LDO e escolha da peça.", "/planejamento/proposta-orcamentaria/[id] · scripts/percurso-v31-contador.ts."),
  "5.9.3.26": m("PARCIAL", "cronograma mensal de desembolso por fonte x mês, versionado por ato (proporCmdDaLoa, registrarVersaoCmd; m02-programacao.test.ts t1, t1b), tela /planejamento/cmd-mba e PDF /planejamento/cmd-mba/pdf (smoke-programacao-financeira.ts). FALTA: recorte por entidade e tela para valores manuais por mês (só proposta uniforme da LOA).", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts."),
  "5.9.3.27": m("PARCIAL", "metas de arrecadação por fonte no MBA, com PDF e confronto com o arrecadado (confrontoMba, m02-programacao.test.ts t8). FALTA: grão mensal (é bimestral), entidade, e tela para digitar valores diferentes por período.", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts."),
  "5.9.3.28": m("PARCIAL", "cada decreto tem 'Imprimir decreto' (app/(areas)/planejamento/creditos-adicionais/decreto/route.ts, montarDecreto em lib/pdf/operacionais.ts) com identificação, itens e totais. FALTA: teste e percurso que exerçam a rota, e o texto jurídico do decreto (o gerador por modelo existe só para CMD e MBA)."),
  "5.9.3.29": m("PARCIAL", "modo diferente: implantar é efetivar a proposta, única por exercício (EfetivacaoDaProposta); depois disso, ajustar e importar de novo são recusados (m02-proposta-orcamentaria.test.ts). FALTA: recusar inclusão de ficha e receita prevista no exercício já efetivado fora do caminho de crédito e reprevisão.", "/planejamento/proposta-orcamentaria/[id] · scripts/percurso-v31-contador.ts C.6."),
  "5.9.3.30": m("PARCIAL", "elaborarProposta importa fichas e receitas do exercício de origem, com valor de partida, reajuste e fichas exclusivas, sem tocar o razão até a efetivação (m02-proposta-orcamentaria.test.ts; percurso-v31-contador.ts C.1, D.4). FALTA: copiar relacionamentos e configurações (o subtipo da dedução precisa ser registrado de novo — pendência PROPOSTA-SUBTIPO-DA-DEDUCAO).", "/planejamento/proposta-orcamentaria · scripts/percurso-v31-contador.ts."),
  "5.9.3.32": m("PARCIAL", "modo diferente: a cota é fonte x mês do cronograma, cobrada no empenho dentro da transação (modules/m05-despesa/guard-cmd.ts; m02-programacao.test.ts t2 a t7, concorrência em t7), ligada por ato na tela /planejamento/cmd-mba; o percurso recusa empenho acima da cota. FALTA: cota por entidade ou por dotação.", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts (recusa de 20.000,00 contra cota de 12.500,00)."),
  "5.9.3.33": m("AUSENTE_CONFIRMADO", "a cota de despesa tem grão fixo mensal e a meta de receita grão fixo bimestral (programacao-dominio.ts); não há periodicidade configurável."),
  "5.9.3.34": m("AUSENTE_CONFIRMADO", "os créditos adicionais (modules/m03-creditos) não tocam CotaCmd; mudar cota exige nova versão do cronograma ou liberação. FALTA: atualização automática das cotas pela alteração orçamentária."),
  "5.9.3.35": m("AUSENTE_CONFIRMADO", "a tela e o PDF do cronograma mostram cotas e liberações, sem coluna de realizado (empenhado); o consumido existe só dentro do guard (guard-cmd.ts). FALTA: previsto x realizado das cotas de despesa."),
  "5.9.3.36": m("PARCIAL", "existe a alternativa [c]: distribuirEmParcelas divide por 12 com resto na última (programacao-dominio.ts, teste t1), proposta pela tela. FALTA: [a] executado no ano anterior e [b] média dos últimos três anos.", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts."),
  "5.9.3.37": m("AUSENTE_CONFIRMADO", "não há percentual por mês no cronograma; registrarVersaoCmd aceita cotas manuais sem tela e sem divisão por percentual."),
  "5.9.3.38": m("PARCIAL", "modo diferente: a limitação de empenho do art. 9º da LRF é feita por cota — ligada por ato com motivo e data (registrarEventoLimitacao) e cobrada no empenho (guard-cmd.ts; m02-programacao.test.ts t2 a t5; smoke-programacao-financeira.ts). FALTA: contingenciamento por percentual sobre o orçamento todo ou sobre dotação específica.", "/planejamento/cmd-mba · scripts/smoke-programacao-financeira.ts."),
  "5.9.3.39": m("VALIDADO_LOCALMENTE", "modo diferente, mesmo efeito: liberar é devolver cota do mês por ato (liberarProgramacao, FormLiberacao em /planejamento/cmd-mba), que sobe o teto da fonte; o empenho antes recusado passa a ser aceito (m02-programacao.test.ts t4). Ressalva: libera cota por fonte e mês, não valor contingenciado por percentual (ver 5.9.3.38).", "papel: contador · /planejamento/cmd-mba · percurso scripts/smoke-programacao-financeira.ts libera 10.000,00 por ato e o mesmo empenho é aceito."),
  "5.9.3.40": m("PARCIAL", "modo diferente: retirar cota é nova versão do cronograma com valor menor (registrarVersaoCmd; m02-programacao.test.ts t6), e a cota não rola de mês (t3). FALTA: rotina que apure a cota não usada de meses fechados e redistribua nos abertos, e tela de edição por valor."),
  "5.9.3.41": m("PARCIAL", "há conferência, não rotina que iguale as peças: conferencia-da-proposta.ts compara a proposta com as metas da LDO e as ações do PPA (k6, k8; tela Conferencia.tsx). FALTA: o vínculo PPA-LOA (pendência VINCULO-PPA-LOA) e a rotina que aponte e corrija divergências entre as três peças."),
  "5.9.3.42": m("PARCIAL", "a conferência da proposta mostra despesa x receita por fonte e acusa fontes sem lastro (código FONTES, teste k2); a LOA tem os anexos da Lei 4.320, com o Anexo 8 por natureza declarada da fonte. FALTA: consulta receita x despesa da LOA por fonte, com seleção de entidades e impressão."),
  "5.9.3.43": m("PARCIAL", "/relatorios/atualizacoes-orcamentarias com PDF lista cada movimento de crédito com decreto, lei, origem, ficha, UG, fonte, tipo e situação (test/ui/atualizacoes-orcamentarias.test.ts, N=3 fichas), filtrando por ficha, decreto, fonte e UG. FALTA: filtros de data, tipo de crédito e origem, agrupamento por órgão, programa, ação, função e subfunção, e percurso que aplique filtro."),
  "5.9.3.44": m("PARCIAL", "existem os demonstrativos de execução de MDE (rreo-anexo8.ts), saúde (rreo-anexo12.ts) e pessoal (rgf-anexo1.ts), com teste e tela. FALTA: os mesmos mínimos calculados sobre os valores ORÇADOS (LOA ou proposta) — a conferência da proposta não os traz (pendência PROPOSTA-CONFERENCIA-ANTES-DA-VOTACAO)."),

  // ═══ 5.10.1 ESCRITURAÇÃO ═══
  "5.10.1.1": m("PARCIAL", "a escrituração passa por um funil único (lancarNoRazao em modules/m01-core-contabil/razao.ts, vigiado por m01-funil.test.ts), append-only, balanceada por subsistema, com roteiros fail-closed, leiautes de tribunal em adapters/tribunais/ e demonstrativos no M12. Cláusula global: atendimento é medido nas cláusulas específicas. FALTA: SEFIP e eSocial (leiaute externo ausente)."),
  "5.10.1.2": m("PARCIAL", "empenho, liquidação, pagamento e retenção lançam na mesma transação do fato; o funil único impede escritor paralelo; conferirDotacaoContraRazao confronta razão e dotação. FALTA: o lançamento manual (FormsDoLancamentoManual.tsx, para ajuste e abertura) registra partidas sem origem em cadastro — a proibição vale para o fluxo da despesa, não para toda a escrituração."),
  "5.10.1.4": m("VALIDADO_LOCALMENTE", "empenho, liquidação e pagamento lançam por fase, balanceados por subsistema, com roteiro parametrizado (modules/m05-despesa/servico.ts, servico-bloco2.ts; m05.test.ts, m05b.test.ts, m05-concorrencia.test.ts).", "papel: EMPENHAR/LIQUIDAR/PAGAR · /despesa/empenhos, /despesa/liquidacoes, /despesa/pagamentos · percursos scripts/smoke-cadeia-despesa.ts (cadeia com retenção e estorno) e scripts/demonstracao/percurso-execucao-da-despesa.ts."),
  "5.10.1.5": m("IMPLEMENTADO_NAO_VALIDADO", "o travamento por competência (M16) vale para todo fato porque o funil o consulta (m16-travamento.test.ts t1 a t7b: mês travado rejeita, dia seguinte passa, concorrência não atravessa); exclusão não existe (razão append-only, correção é estorno, que também passa pelo guard). A tela /contabilidade/fechamento-mensal trava o mês (percurso-v33.ts C.4 a C.6). FALTA: percurso que tente lançar em mês fechado pela tela e leia a recusa."),
  "5.10.1.6": m("VALIDADO_LOCALMENTE", "TipoEmpenho ORDINARIO, GLOBAL e ESTIMATIVO; m05-tipo-do-empenho.test.ts prova a regra do MCASP com N=2 parcelas; FormEmpenho.tsx tem o seletor.", "papel: EMPENHAR · /despesa/empenhos · percurso scripts/demonstracao/percurso-execucao-da-despesa.ts (passo 3 afirma o tipo)."),
  "5.10.1.7": m("AUSENTE_CONFIRMADO", "não há subempenho no modelo (já registrado em 5.17.98); o global aceita várias liquidações (m05-tipo-do-empenho.test.ts), mas não há a entidade subempenho nem o bloqueio de subempenho sobre global já liquidado."),
  "5.10.1.9": m("VALIDADO_LOCALMENTE", "V36: o empenho ganhou a busca da dotação — um campo filtra as fichas por número, natureza e título, fonte, unidade e função.subfunção.programa.ação com o título da ação, sem caixa nem acento, vários termos restringindo; a ficha escolhida não some (app/(areas)/despesa/empenhos/busca-da-ficha.ts; listarFichas traz a classificação; test/ui/busca-da-ficha.test.ts, mutação acusada).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-busca-da-ficha.mts, 4/4: em 1.054 fichas, '339014' deixa 34; um segundo termo restringe."),
  "5.10.1.10": m("PARCIAL", "exigirSaldo (modules/m05-despesa/adapter-prisma.ts) recusa empenho acima do disponível dentro da transação (m05.test.ts); a tela mostra o disponível atual (percurso-execucao-da-despesa.ts passo 2). FALTA: saldo da dotação até a data de emissão, para empenho retroativo.", "/despesa/empenhos · scripts/demonstracao/percurso-execucao-da-despesa.ts."),
  "5.10.1.11": m("AUSENTE_CONFIRMADO", "não há marca de contribuinte autônomo em pessoa, credor, empenho ou liquidação (TipoDePessoa só FISICA e JURIDICA); pessoa física é NAO_CALCULAVEL na retenção. SEFIP e eSocial dependem de leiaute externo."),
  "5.10.1.12": m("AUSENTE_CONFIRMADO", "não há ação de duplicar empenho em modules/m05-despesa, app/(areas)/despesa ou lib/portas."),
  "5.10.1.14": m("VALIDADO_LOCALMENTE", "modules/m05-despesa/adiantamentos.ts concede diária e suprimento e lança o controle (classes 7 e 8) pelas contas que o ente declara; a aprovação da prestação baixa o controle e, desde a V35, só aceita devolução coberta pelas anulações (m05-adiantamentos.test.ts t1 a t5; m05-adiantamentos-movimento.test.ts m1 a m3). Modo diferente: o controle nasce na concessão que referencia o empenho, não na emissão do empenho — o empenho só vira responsabilidade a comprovar quando há beneficiário e período.", ROTA_ADIANTAMENTOS),
  "5.10.1.15": m("VALIDADO_LOCALMENTE", "anulação total e parcial de empenho como fato novo, com motivo obrigatório (anulacao-parcial.ts, servico-bloco2.ts; m05-anulacao-parcial.test.ts). V36: a NOTA DE ESTORNO em PDF (/despesa/anulacoes/nota) para anulação de empenho, liquidação ou pagamento — número, data, documento anulado, integral ou parcial, valor, motivo, autor e as partidas do lançamento (lib/pdf/nota-de-estorno.ts; test/ui/nota-de-estorno.test.ts, N=2). O percurso achou e a V36 corrigiu um 500 da central de anulações na primeira anulação registrada.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-nota-de-estorno.mts, 4/4: anulação pelo painel antes de encerrar → central → nota em PDF → tipo errado 404."),
  "5.10.1.16": m("PARCIAL", "apropriarFolha (modules/m33-folha/apropriacao.ts) empenha a folha fechada pelo empenhar do M05, por grupo de empenho, nos tipos mensal, complementar, adiantamento do 13º, 13º e adiantamento salarial (m33-apropriacao.test.ts, m33-criterio-do-abatimento.test.ts, m33-adiantamento-salarial.test.ts). FALTA: folha de férias como tipo próprio (depende do Estatuto do município).", "/folha/folhas/[id] · scripts/smoke-apropriacao-da-folha.ts, scripts/smoke-decimo-terceiro.ts."),
  "5.10.1.17": m("PARCIAL", "a apropriação recusa rubrica sem grupo e para dizendo a ficha e a matrícula quando falta saldo, sem duplicar na retomada (m33-apropriacao.test.ts). FALTA: consulta prévia listando todas as irregularidades antes de gravar.", "/folha/folhas/[id] · scripts/smoke-apropriacao-da-folha.ts."),
  "5.10.1.18": m("IMPLEMENTADO_NAO_VALIDADO", "modules/m33-folha/apropriacao-por-competencia.ts lança a provisão mensal do 13º e das férias por vínculo, com encargos patronais; a liquidação baixa o passivo; o acerto de 31/12 zera o 13º (m33-apropriacao-por-competencia.test.ts t1 a t6, dois vínculos, três mutações). FALTA: percurso de navegador em /folha/apropriacao-por-competencia."),
  "5.10.1.19": m("PARCIAL", "a liquidação da folha vem depois da certificação, com segregação (modules/m33-folha/certificacao.ts; smoke-atesto-da-folha.ts); as retenções viram MovimentoExtraorcamentario no pagamento (descontos-da-folha.ts; m07-retencao.test.ts). Modo diferente: a nota extra nasce no pagamento, não na liquidação. FALTA: liquidação automática e reconhecimento da consignação na liquidação.", "/folha/folhas/[id] · scripts/smoke-atesto-da-folha.ts."),
  "5.10.1.20": m("AUSENTE_CONFIRMADO", "não existe desmovimentar competência da folha: o MODULO do M33 registra RETIFICACAO-DA-FOLHA; cálculo fechado não se recalcula; desfazer empenhos é anulação pela despesa, um a um."),
  "5.10.1.21": m("PARCIAL", "o fluxo existe em etapas por ator: RH calcula e fecha, contabilidade apropria, atestador certifica, liquidante liquida, tesouraria paga; EmpenhosDaFolha.tsx mostra por empenho a liquidação e o pagamento (smoke-atesto-da-folha.ts, cinco papéis). FALTA: estado final 'folha concluída' quando todos os empenhos estão pagos.", "/folha/folhas/[id] · scripts/smoke-atesto-da-folha.ts."),
  "5.10.1.23": m("VALIDADO_LOCALMENTE", "o contrato é cadastrado uma vez no M11 (Contrato) e consumido pelo empenho, pela liquidação, pela ordem de compra e pelo saldo do contrato (m11-integracao.test.ts, m05-concorrencia.test.ts).", "papel: EMPENHAR · /licitacoes/contratos, /despesa/empenhos · percursos scripts/smoke-contratacao.ts (passo 5) e scripts/smoke-ponte-contratual.ts."),
  "5.10.1.24": m("PARCIAL", "a reserva de dotação existe (reservarDotacao, tela em /planejamento/fichas/[id]); empenhar à conta da reserva a libera e o disponível cai uma vez (m05.test.ts; smoke-contratacao.ts). FALTA: bloqueio automático na emissão da requisição ou ordem de compra (o M11 não reserva).", "/planejamento/fichas/[id] · scripts/smoke-contratacao.ts."),
  "5.10.1.26": m("PARCIAL", "modules/m05-despesa/dossie.ts monta a consulta do empenho com origem, dotação, ordem de compra, contrato, processo, liquidações, retenções, pagamentos, anulações nos três níveis, lançamentos e histórico (m05-dossie.test.ts, 11 casos), tela /despesa/empenhos/[id]. FALTA: anexos, assinantes e o processo digital no dossiê.", "/despesa/empenhos/[id] · scripts/smoke-cadeia-despesa.ts, scripts/demonstracao/percurso-execucao-da-despesa.ts."),
  "5.10.1.27": m("PARCIAL", "o detalhe do resto (/despesa/restos-a-pagar/[id]) mostra origem e composição do saldo; desde a V36 o empenho de origem abre o dossiê, que traz contrato, liquidações, retenções, anulações e lançamentos (dossieDoEmpenho). FALTA: percurso — nenhuma base local tem resto inscrito; anexos e assinantes não estão no dossiê."),
  "5.10.1.29": m("PARCIAL", "a retenção gera a nota extra (MovimentoExtraorcamentario) presa ao pagamento, com cálculo de IRRF, INSS e ISS por tabela e perfil do fornecedor (retencao-calculada.ts; m07-retencao*.test.ts). Modo diferente: o momento é o pagamento, não a liquidação (pendência RETENCOES-NA-LIQUIDACAO-DA-PARCELA).", "/despesa/pagamentos, /financeiro/extraorcamentario · scripts/smoke-cadeia-despesa.ts, scripts/demonstracao/percurso-retencao-calculada.ts."),
  "5.10.1.30": m("AUSENTE_CONFIRMADO", "a liquidação exige empenho existente e não tem indicação de despesa sem empenho prévio (zLiquidarInput, Liquidacao)."),
  "5.10.1.31": m("PARCIAL", "a liquidação aceita documento fiscal conferido (DocumentoFiscalRecebido: NFE, NFCE, avulsa, CTE, RPS, recibo, outro) ou a nota inline (FormLiquidacao.tsx; percurso-execucao-da-despesa.ts). FALTA: vários documentos por liquidação e controle de pessoa estrangeira.", "/despesa/liquidacoes · scripts/demonstracao/percurso-execucao-da-despesa.ts."),
  "5.10.1.32": m("PARCIAL", "documento fiscal duplicado (emitente+modelo+série+número, e chave de acesso) é recusado com motivo (registrarDocumentoFiscal; m11-documento-fiscal.test.ts t3, t4; smoke-compras.ts), e a liquidação só aceita nota conferida do credor. FALTA: o parâmetro de configuração, e conferência quando a nota é digitada na liquidação sem documento registrado.", "/licitacoes/documentos-fiscais · scripts/smoke-compras.ts."),
  "5.10.1.33": m("PARCIAL", "modo diferente, mesmo efeito: não se altera liquidação — anula-se total ou parcialmente (registro novo) e liquida-se de novo (anulacao-parcial.ts; m05b.test.ts, m05-anulacao-parcial.test.ts t2), na central /despesa/anulacoes. FALTA: percurso que anule liquidação pela tela, e teste e campo de tela para a substituição de documento fiscal (substituiId)."),
  "5.10.1.34": m("PARCIAL", "a liquidação de material aceita entradas de material por classe, com perna física (FormLiquidacao.tsx; smoke-cadeia-por-papel.ts, smoke-ent06.ts). FALTA: itens do empenho e da liquidação fora de material, e a carga dos itens do empenho."),
  "5.10.1.35": m("DEPENDENCIA_EXTERNA", "docs/dependencias-externas.md registra a consulta de NF-e na Receita como ausente, não solicitada; o sistema guarda a chave de 44 dígitos e importa o XML com validação estrutural (xml-nfe.ts, xml-nfe.test.ts). FALTA: o estado 'consulta indisponível' nomeado na tela."),
  "5.10.1.36": m("VALIDADO_LOCALMENTE", "empenho, liquidação, pagamento, anulações e cancelamento de restos lançam no razão por roteiro na mesma transação (m05.test.ts, m05b.test.ts, m05-dotacao-razao.test.ts, m08-anulacao-cancelamento.test.ts, m08-controle-dos-restos.test.ts). Ressalva: o estágio facultativo 'em liquidação' não é usado (5.10.1.42).", "papel: EMPENHAR/LIQUIDAR/PAGAR/CANCELAR · /despesa/empenhos, /despesa/liquidacoes, /despesa/anulacoes, /despesa/restos-a-pagar · percursos scripts/smoke-cadeia-despesa.ts, scripts/smoke-restos-a-pagar-operacoes.ts."),
  "5.10.1.38": m("AUSENTE_CONFIRMADO", "nenhuma validação de débito do credor no empenho, na liquidação ou no pagamento; a dívida ativa (M10) e os lançamentos (M34) existem isolados."),
  "5.10.1.39": m("IMPLEMENTADO_NAO_VALIDADO", "empenho com contrato é recusado na transação por processo não homologado, contrato fora da vigência (com prorrogações) e saldo do contrato insuficiente (adapter-prisma.ts do M05, adapter-m05.ts do M11; m11-integracao.test.ts t2 e t3). FALTA: percurso que exerça as recusas pela tela."),
  "5.10.1.40": m("PARCIAL", "ao empenhar com contrato exige-se processo homologado e, com reserva, que reserva e contrato sejam do mesmo processo (m11-integracao.test.ts). FALTA: vigência do processo ou da ata, e consistência para empenho ligado a processo sem contrato."),
  "5.10.1.41": m("PARCIAL", "modo diferente: o destino VPD ou ativo é decidido por elemento, declarado pelo ente em ContaDaLiquidacaoPorElemento (conta-da-liquidacao.ts; m01-conta-da-liquidacao.test.ts; tela /contabilidade/contas-da-liquidacao, percurso-v28-cadeias.ts); estoque entra por entradas de material. FALTA: escolha por liquidação e itens da nota para bens permanentes e serviços.", "/contabilidade/contas-da-liquidacao · scripts/demonstracao/percurso-v28-cadeias.ts."),
  "5.10.1.42": m("AUSENTE_CONFIRMADO", "o estágio 'em liquidação' (6.2.2.1.3.02) está DORMENTE em modules/m01-core-contabil/roteiros.ts; não há relatório de empenhos e restos em liquidação. O estágio é facultativo no MCASP."),
  "5.10.1.43": m("PARCIAL", "reserva de dotação por valor e liberação como registro novo, lançadas no razão (reservarDotacao, liberarReserva, dotacao-razao.ts; m05.test.ts, m05-dotacao-razao.test.ts t3), tela /planejamento/fichas/[id] e percurso-v31-rastreio.ts D.1 a D.4. FALTA: bloqueio por percentual e bloqueio distinto de reserva.", "/planejamento/fichas/[id] · scripts/percurso-v31-rastreio.ts."),
  "5.10.1.45": m("AUSENTE_CONFIRMADO", "o M36 (prisma/schema/m36-frota.prisma) tem veículo, máquina e abastecimento, sem multa nem infrator."),
  "5.10.1.47": m("VALIDADO_LOCALMENTE", "o dossiê do empenho (/despesa/empenhos/[id]; modules/m05-despesa/dossie.ts; m05-dossie.test.ts) reúne origem, liquidações, pagamentos, retenções, anulações e lançamentos; desde a V36 cada linha do histórico leva ao fato na própria página (âncora da liquidação ou do pagamento) e ao lançamento contábil que ele gerou.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-elos.mts, 15/15: dossiê de um empenho pago → histórico com 4 links de lançamento → o link abre o lançamento."),
  "5.10.1.49": m("DEPENDENCIA_EXTERNA", "docs/dependencias-externas.md registra a consulta de NF-e emitidas contra a entidade na SEFAZ como ausente, não solicitada. Depende de contrato e credencial."),
  "5.10.1.50": m("PARCIAL", "cadastro de obras (Obra, cadastrarObra; m11-obras.test.ts) com identificador, descrição, tipo, CEI, órgão, anexos e campos adicionais, tela /licitacoes/obras e percurso smoke-ent03c.ts. FALTA: localização, valor, conta de incorporação, contrato e licitação como campos.", "/licitacoes/obras · scripts/smoke-ent03c.ts."),
  "5.10.1.51": m("IMPLEMENTADO_NAO_VALIDADO", "Empenho.obraId existe e o elemento 51 exige obra ativa (m11-obras.test.ts t3, t3b). V36: o link 'empenhos desta obra' (e os de convênio, precatório, consórcio e dívida) era morto — o relatório gerencial ignorava o parâmetro. Agora o recorte por vínculo desce ao SQL com as anulações (m05-consultas-execucao.test.ts t6, mutação acusada), a tela e o PDF imprimem o nome do registro e vínculo inexistente é recusado (percurso-v36-leituras). FALTA: percurso com uma obra que tenha empenho."),
  "5.10.1.52": m("PARCIAL", "o detalhe da obra mostra dados, órgão, medições com contrato, responsável e aprovação, anexos e planilha orçamentária (m11-medicoes-integracao.test.ts; smoke-ent03c.ts, smoke-planilha-da-obra.ts). FALTA: aditivos, licitação, empenhos e situação da obra.", "/licitacoes/obras/[id] · scripts/smoke-ent03c.ts."),
  "5.10.1.53": m("AUSENTE_CONFIRMADO", "a obra mostra medido e aprovado; não há valor da obra, valor contratado, empenhado nem percentual executado."),
  "5.10.1.54": m("AUSENTE_CONFIRMADO", "o portal da transparência não tem obras; modules/m13-transparencia/MODULO.md lista obras entre o que não foi feito."),
  "5.10.1.55": m("PARCIAL", "o detalhe da ficha traz chave, dotação inicial, saldos, histórico dos movimentos, reservas e empenhos (lib/portas/operacoes-da-ficha.ts; m05-dotacao-razao.test.ts, m03-qdd.test.ts; percurso-v31-rastreio.ts). FALTA: relatório analítico único de dotações com filtro por qualquer campo.", "/planejamento/fichas/[id] · scripts/percurso-v31-rastreio.ts."),
  "5.10.1.56": m("AUSENTE_CONFIRMADO", "o mecanismo existe (liquidações de capital com valor a incorporar e a reclassificação na incorporação, m10-patrimonio.test.ts), mas não o relatório de bens incorporados e não incorporados com filtros."),
  "5.10.1.57": m("PARCIAL", "/despesa/empenhos lista empenhado, liquidado, pago e saldos no recorte autorizado, com CSV, Excel e PDF (m05-consultas-execucao.test.ts); /relatorios/gerenciais filtra por credor e fonte; restos têm filtro e relatório próprio. FALTA: filtros por todos os campos da dotação, obra e licitação, e totalizar sem listar.", "/despesa/empenhos · scripts/demonstracao/percurso-execucao-da-despesa.ts."),
  "5.10.1.58": m("PARCIAL", "os anexos da Lei 4.320 da LOA saem com valores fixados (anexos/loa.ts; m02b-anexos-loa.test.ts; /planejamento/loa e /transparencia/planejamento/loa/[exercicio]); o RREO Anexo 2 cobre função e subfunção com execução. FALTA: colunas de execução (empenhado, liquidado, pago) nesses quadros e as visões por elemento, ação, órgão e unidade."),
  "5.10.1.59": m("AUSENTE_CONFIRMADO", "não há página de audiência com gráficos comparativos; os demonstrativos de base (RGF, RREO, metas da LDO, limites) existem."),
  "5.10.1.60": m("PARCIAL", "concessão e prestação de contas de diária e suprimento existem (adiantamentos.ts), e a solicitação de empenho tem autorização por outro usuário (solicitacao-de-empenho.ts). FALTA: solicitação de diária ou adiantamento em fluxo configurável que termine no empenho.", "/despesa/adiantamentos · scripts/demonstracao/percurso-v32-areas.ts."),
  "5.10.1.61": m("VALIDADO_LOCALMENTE", "concessão, prestação e aprovação (adiantamentos.ts) lançam o controle nas classes 7 e 8 pelas contas declaradas; a despesa segue empenho, liquidação e pagamento (m05-adiantamentos.test.ts t1 a t5; m05-adiantamentos-movimento.test.ts m1 a m3). O percurso da V36 refez o caminho depois da guarda da devolução (V35) e achou um defeito de tela, corrigido: a mensagem de sucesso sumia junto com o formulário trocado.", ROTA_ADIANTAMENTOS),
  "5.10.1.62": m("AUSENTE_CONFIRMADO", "não há prestação de contas online pela entidade beneficiada: a prestação é registrada por servidor interno; não há perfil externo vinculado à concessão."),
  "5.10.1.63": m("AUSENTE_CONFIRMADO", "PrestacaoDeContasDoAdiantamento guarda valores e relatório, sem anexo; não há tela filtrada pela entidade logada."),
  "5.10.1.64": m("PARCIAL", "cada prestação fica registrada append-only; o analista aprova ou rejeita com motivo e a rejeição reabre para nova apresentação (aprovar/rejeitarPrestacaoDeAdiantamento). FALTA: o canal online da entidade (5.10.1.62)."),
  "5.10.1.65": m("PARCIAL", "a aprovação gera a baixa automática do controle pelo roteiro declarado, sob trinco e com a devolução conferida (m05-adiantamentos.test.ts t1; m05-adiantamentos-movimento.test.ts). FALTA: a origem online (5.10.1.62)."),
  "5.10.1.70": m("PARCIAL", "o prazo é dado por concessão, a situação EM_ATRASO é derivada e concederAdiantamento recusa novo suprimento a quem está em atraso ou com dois em aberto (m05-adiantamentos.test.ts t3, N=2, mutação do art. 69). FALTA: a regra vale só para suprimento (não diária), não há prazo configurável por espécie, e a recusa não foi exercida pela tela."),
  "5.10.1.73": m("VALIDADO_LOCALMENTE", "razão de partidas dobradas com funil único (lancarNoRazao; packages/ledger validarLancamento) conferindo débito = crédito por subsistema (m01.test.ts, m01-funil.test.ts, m01-consolidacao.test.ts); Livro Diário em /relatorios/livros/diario (m12-livros.test.ts t1, t5, t7).", "/contabilidade/lancamentos, /relatorios/livros/diario · percursos scripts/percurso-v31-rastreio.ts e scripts/percurso-v33-cadeias.ts."),
  "5.10.1.76": m("AUSENTE_CONFIRMADO", "a fila de assinaturas do M22 cobre empenho, liquidação, ordem de pagamento e borderô; os movimentos extraorçamentários não têm documento canônico nem ação de assinar."),
  "5.10.1.92": m("PARCIAL", "a abertura orçamentária é automática: a ficha grava a dotação inicial e a previsão da receita lança D 5.2.1.1.1 / C 6.2.1.1 (previsao-no-razao.ts, V35); a efetivação da proposta faz as duas numa transação (m02-proposta-orcamentaria.test.ts; percurso-v31-contador.ts). FALTA: abertura por entidade, e previsões anteriores à V35 sem lançamento.", "/planejamento/proposta-orcamentaria · scripts/percurso-v31-contador.ts."),
  "5.10.1.96": m("PARCIAL", "modo diferente: o superávit por fonte é apurado dos fatos (superavit-por-fonte.ts, consulta-do-superavit.ts, amarrações S1 a S3; m12-superavit-fonte.test.ts), exposto em /contabilidade/superavit e usado como teto pelo M03; a fonte atravessa o exercício nos fatos, não por lançamento de abertura. FALTA: detalhe por conta bancária e percurso da tela."),
  "5.10.1.97": m("IMPLEMENTADO_NAO_VALIDADO", "modules/m12-relatorios/consistencia.ts confere, no escopo anual, balancete, balanço patrimonial, DVP, balanço orçamentário e eliminações intra, com OK, DIVERGE ou SEM_DADO (m12-consistencia.test.ts), tela /relatorios/consistencia; desde a V36 o painel 'antes de encerrar' da tela de restos leva a ela (percurso-v36-leituras). FALTA: percurso que mostre uma divergência e o encerramento não a exige."),
  "5.10.1.98": m("VALIDADO_LOCALMENTE", "o encerramento é feito em etapas separadas, cada uma com tela e confirmação digitada: encerrar e inscrever restos (encerrarExercicioComRestos, que desde a V35 também lança o controle 5.3/6.3), apurar o resultado (classes 3 e 4) e virar os controles 5 e 6 (m08-encerramento.test.ts, m08-encerramento-cadeia.test.ts, m08-encerramento-controles.test.ts, m08-controle-dos-restos.test.ts). Ressalva: sem painel único de progresso.", "/despesa/restos-a-pagar, /contabilidade/virada-dos-controles · percursos scripts/smoke-encerramento-do-exercicio.ts, scripts/percurso-v33-encerramento.ts, scripts/smoke-virada-dos-controles.ts."),
  "5.10.1.99": m("AUSENTE_CONFIRMADO", "não há cópia de programações de pagamento (lotes e borderôs) para o exercício seguinte; o liquidado e não pago vira resto a pagar."),
  "5.10.1.100": m("VALIDADO_LOCALMENTE", "modo diferente: o encerramento continua inscrevendo todo saldo a liquidar (a inscrição é do saldo), e a V36 pôs ANTES dele, na tela de restos a pagar, a lista dos empenhos ESTIMATIVOS com saldo, com a anulação parcial ali mesmo (a mesma da central: motivo, ato novo). Recorte por tipo no M05 alcançando as anulações pelo original (m05-consultas-execucao.test.ts t7, mutação acusada).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-leituras.mts, 6/6: /despesa/restos-a-pagar → painel 'antes de encerrar' lista 6 estimativos de 2026 com saldo, cada um com o formulário de anulação."),
  "5.10.1.103": m("IMPLEMENTADO_NAO_VALIDADO", "modo diferente: não há cópia de notas extraorçamentárias porque o saldo a pagar por consignatário (listarSaldosExtra) não tem recorte de exercício — a obrigação atravessa a virada sem cópia; m07-composicao-do-recolhimento.test.ts t1 recolhe numa guia retenções de 2026 e 2027. FALTA: prova com exercício encerrado e recolhimento no ano novo."),
  "5.10.1.105": m("PARCIAL", "/contabilidade/lancamentos é a consulta analítica do razão com filtros por período, conta, subsistema, origem, fonte e fato, e o detalhe mostra origem, natureza, estorno e autor (m12-livros.test.ts t5; percurso-v31-rastreio.ts). FALTA: conta corrente da MSC no lançamento (resolvida só na exportação), conta corrente do estado e o evento do roteiro.", "/contabilidade/lancamentos · scripts/percurso-v31-rastreio.ts."),
  "5.10.1.106": m("PARCIAL", "o balancete dá saldos por conta com anterior, período e acumulado (/relatorios/livros/balancete; m12-livros.test.ts t2 a t4) e o fechamento mensal confere mês a mês. FALTA: saldos por fonte de recursos e visão de doze meses lado a lado."),
  "5.10.1.107": m("IMPLEMENTADO_NAO_VALIDADO", "V36 corrigiu o defeito: com filtro de conta, os totais da página e a soma da seleção (SelecaoESoma.tsx) passam a somar só as partidas da conta — antes incluíam as contrapartidas e a diferença dava zero sempre. totaisPorSubsistema(lancamentos, conta) em modules/m12-relatorios/livros.ts, m12-totais-da-conta.test.ts (N=2, mutação acusada). Os totais da conta foram vistos pela tela (percurso-v36-leituras: 2.191.558,86 de movimento dos bancos). FALTA: percurso que marque lançamentos e leia a soma da seleção."),
  "5.10.1.109": m("VALIDADO_LOCALMENTE", "o Livro Diário (diario() em modules/m12-relatorios/livros.ts) sai em PDF (/relatorios/livros/diario/pdf) com TERMO DE ABERTURA e TERMO DE ENCERRAMENTO: entidade, CNPJ, período, contagem de lançamentos, primeiro e último número, totais de débito e crédito, contador com CRC e ordenador do cadastro institucional (campo vazio sai 'não cadastrado', nunca inventado). lib/pdf/livros.ts; test/ui/livros-com-termos.test.ts (N=2, mutação do total acusada).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-livros.mts, 5/5."),
  "5.10.1.110": m("PARCIAL", "o Razão por conta (razaoAnalitico; m12-livros.test.ts t2, t6) sai em PDF desde a V36 (/relatorios/livros/razao/pdf) com termo de abertura e de encerramento, saldo anterior, movimentos com saldo corrente, totais e saldo final (test/ui/livros-com-termos.test.ts; percurso-v36-livros.mts). FALTA: agrupamento por data ou tipo de lançamento e resumo por fonte de recursos.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-livros.mts (Razão da conta de bancos em PDF; sem conta, 400)."),
  "5.10.1.111": m("AUSENTE_CONFIRMADO", "o balancete é por conta, sem recorte por fonte; a fonte existe nos fatos (arrecadadoPorFonte, despesaPorFonte, extraorcamentarioPorFonte, restosAPagarPorFonte) mas não há balancete por fonte."),
  "5.10.1.112": m("PARCIAL", "há dois relatórios equivalentes por fonte: RGF Anexo 5 (rgf-anexo5.ts; m12-rgf-anexo5.test.ts) com disponibilidade bruta, obrigações, restos, consignações e disponibilidade líquida por fonte, e o superávit por fonte (m12-superavit-fonte.test.ts). FALTA: seleção de uma ou mais fontes e percurso."),
  "5.10.1.113": m("AUSENTE_CONFIRMADO", "o recolhimento compõe a guia com as retenções que quita, mas o sistema não emite DARF, GPS, DARF do PASEP nem recibo de retenção de IRRF e ISSQN; o MODULO do M07 declara a guia fora do escopo."),
  "5.10.1.114": m("PARCIAL", "/financeiro/extraorcamentario lista retenções (com drill ao pagamento e empenho), dispêndios e saldos por consignatário, com PDF (modules/m07-extraorcamentario/consultas.ts; percurso-retencoes-proprias.ts, smoke-recolhimento-por-origem.ts). FALTA: filtros por credor, conta, fonte e empenho, separação emitidas/estornadas/pagas e totalização.", "/financeiro/extraorcamentario · scripts/smoke-recolhimento-por-origem.ts."),

  // ═══ 5.10.2 FINANCEIRO ═══
  "5.10.2.1": m("VALIDADO_LOCALMENTE", "pagamento, recebimento, movimentação bancária e transferência entre UGs lançam no razão na mesma transação do registro (M05, modules/m04-receita, registrarMovimentoBancario; m04.test.ts, m09-movimentacao.test.ts, m09-transferencia-entre-ugs.test.ts).", "/despesa/pagamentos, /receita/arrecadacoes, /financeiro/movimentacao · percursos scripts/smoke-cadeia-despesa.ts, scripts/smoke-ent03a.ts, scripts/demonstracao/percurso-dinheiro-nas-telas.ts."),
  "5.10.2.2": m("VALIDADO_LOCALMENTE", "/despesa/pagamentos lista os pagamentos do exercício; o relatório de pagamentos efetuados (/relatorios/pagamentos) traz na mesma consulta os de RESTOS A PAGAR, com retido e líquido, e desde a V36 os DISPÊNDIOS EXTRAORÇAMENTÁRIOS do período numa seção própria (recolhimento a consignatário, devolução de caução), com o estorno descontado, fora do total dos pagamentos, também no CSV e no PDF; só a quem lê o financeiro do ente, e com recorte por unidade a seção diz o motivo (modules/m07-extraorcamentario/dispendios-efetuados.ts; m07-dispendios-efetuados.test.ts, dia civil em hora de borda, mutação do estorno acusada; test/ui/pagamentos-efetuados-pdf.test.ts).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percursos scripts/percurso-v36-pagamentos-efetuados.mts e scripts/percurso-v36-dispendios-extra.mts (4/4: recolhimento registrado pela tela, seção com o total do domínio, total dos pagamentos intacto, motivo com unidade)."),
  "5.10.2.3": m("PARCIAL", "a linha do pagamento oferece estorno total ou parcial append-only (FormAnular; smoke-cadeia-despesa.ts); desde a V36 leva ao lançamento do pagamento e ao empenho na seção do pagamento (percurso-v36-elos.ts). FALTA: anexos no pagamento (o M22 não tem esse alvo).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-elos.mts, 15/15: /despesa/pagamentos → 'lançamento' abre o lançamento do pagamento."),
  "5.10.2.4": m("AUSENTE_CONFIRMADO", "/despesa/pagamentos não tem filtros; o pagamento não tem marca de assinatura, anexo nem finalidade (FUNDEB, FMS)."),
  "5.10.2.5": m("AUSENTE_CONFIRMADO", "não há ação de duplicar em pagamento, movimento bancário, receita, dedução ou transferência."),
  "5.10.2.10": m("PARCIAL", "registrarDeducaoDaReceita (modules/m04-receita/deducao-da-receita.ts; tela /receita/deducoes) registra a dedução pelo bruto e estorna com lançamento novo (m04-deducao-da-receita.test.ts t1 a t7). V36 corrigiu um defeito achado ao semear a base fictícia: o teto somava o arrecadado até o INÍCIO do dia e a dedução no dia do crédito era sempre recusada (t7, mutação acusada). FALTA: subtipos além do FUNDEB e percurso do registro pela tela."),
  "5.10.2.11": m("AUSENTE_CONFIRMADO", "o formulário de dedução trata uma natureza, uma fonte e um valor por envio; não há lote de deduções."),
  "5.10.2.12": m("VALIDADO_LOCALMENTE", "registrarIngressoExtra (modules/m07-extraorcamentario/extraorcamentario.ts) registra caução, depósito e consignação como receita extra sem tocar o orçamento (m07.test.ts). A retenção do pagamento nasce no pagamento, por desenho.", "/financeiro/extraorcamentario · percurso scripts/demonstracao/percurso-sagres-receita-extra.ts (recusa CNPJ com dígito errado, registra o válido)."),
  "5.10.2.13": m("VALIDADO_LOCALMENTE", "modo diferente, mesmo efeito: a nota extra é o dispêndio; /financeiro/extraorcamentario/recolher seleciona várias retenções ou ingressos e gera um recolhimento composto com o vínculo AlocacaoDoRecolhimento (m07-composicao-do-recolhimento.test.ts: exercícios diferentes, composição que não fecha, retenção alheia, repetida, parcial). Ressalva: a seleção é por obrigação (tipo x consignatário).", "/financeiro/extraorcamentario/recolher · percursos scripts/smoke-recolhimento-por-origem.ts, scripts/demonstracao/percurso-dinheiro-nas-telas.ts."),
  "5.10.2.14": m("PARCIAL", "os lançamentos são automáticos e simultâneos ao registro de receita, dedução, extra, movimentação e transferência; a MSC é derivada do razão (modules/m14-exports-federais, m14-msc.test.ts). FALTA: prova de que a MSC leva a conta corrente de cada movimentação financeira (dedução, extra, movimentação bancária)."),
  "5.10.2.16": m("PARCIAL", "receita orçamentária: link do lançamento e estorno pela tela (/receita/arrecadacoes/[id]; smoke-receita-por-fontes.ts). V36: a dedução ganhou o link do lançamento; os ingressos avulsos (caução, depósito) passaram a ser LISTADOS em /financeiro/extraorcamentario (antes só entravam no saldo), com o link do lançamento e o estorno pela tela (estornarMovimentoExtra, já testado), e o percurso registrou, abriu e estornou um ingresso. FALTA: o estorno da dedução pela tela não foi percorrido (só o domínio, m04-deducao-da-receita.test.ts t3).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-elos.mts, 15/15: ingresso registrado pela tela → linha na lista de ingressos avulsos → lançamento aberto → estornado pela tela (no banco, ESTORNO_INGRESSO) → recarga diz 'estornado'; dedução → lançamento aberto."),
  "5.10.2.17": m("AUSENTE_CONFIRMADO", "modo diferente e não equivalente: a dedução do FUNDEB é registro separado pelo valor do demonstrativo do banco (deducao-da-receita.ts diz que não é 20% calculado); a arrecadação da cota-parte não lança a dedução sozinha."),
  "5.10.2.21": m("IMPLEMENTADO_NAO_VALIDADO", "V36: o Anexo do M22 ganhou os donos pagamento e movimento bancário (migration aditiva 20261106130000, duas colunas anuláveis; o dono único continua no zAnexar). O anexo do pagamento segue a UG do pagamento (escopo { pagamento } do M16), o do movimento é ato do ente; o download cobra a leitura do dono (despesa na unidade do pagamento; financeiro do ente). modules/m22-documentos/m22-anexo-do-pagamento-e-do-movimento.test.ts 4/4 (N=2 anexos e donos; quem anexa só noutra unidade é recusado no pagamento; permissão de unidade não basta no movimento; dono inexistente ou duplo recusado com o motivo), três mutações acusadas. Tela: na movimentação bancária, a coluna Documentos abre /financeiro/movimentacao/[id], com os anexos e o formulário. FALTA o percurso: a base fictícia não tem movimento bancário, e registrar um exige a conta contábil de contrapartida, que é decisão do ente — não se escolhe num percurso. A negação (contador vai para /sem-acesso) foi medida."),
  "5.10.2.22": m("AUSENTE_CONFIRMADO", "o borderô existe para lote de pagamento (gerarBordero), não para movimento bancário (depósito, saque, aplicação)."),
  "5.10.2.23": m("VALIDADO_LOCALMENTE", "transferência entre UGs concedida e recebida, com contabilização dos dois lados por tabela (modules/m09-tesouraria/transferencia-entre-ugs.ts; m09-transferencia-entre-ugs.test.ts, 9 casos, N=2). Adm. direta e indireta são modeladas por unidade gestora, o que é equivalente.", "/financeiro/transferencias-entre-ugs · percurso scripts/demonstracao/percurso-v26-cadastros.ts (decide contas, recusa conta alheia, registra dois duodécimos, confere os lançamentos)."),
  "5.10.2.24": m("VALIDADO_LOCALMENTE", "o estorno da transferência inverte os dois lados, recusa repetição e grava motivo, pela tela (percurso-v26-cadastros.ts; m09-transferencia-entre-ugs.test.ts); desde a V36 cada linha leva aos lançamentos da concessão e do recebimento (lancamentoConcedidaId/RecebidaId expostos por conciliacaoDasTransferenciasEntreUgs).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-elos.mts, 15/15: /financeiro/transferencias-entre-ugs → link 'lançamento da concessão' e 'lançamento do recebimento' → /contabilidade/lancamentos/{id} abre o lançamento do duodécimo."),
  "5.10.2.25": m("VALIDADO_LOCALMENTE", "modo diferente, equivalente: a diária é ConcessaoDeAdiantamento de espécie DIARIA com beneficiário, finalidade, destino, período, quantidade, valor unitário, empenho, ato e prazo (prisma/schema/m05-adiantamentos.prisma; m05-adiantamentos.test.ts t1, N=2). Ressalva: o servidor é nome e CPF digitados, não vínculo com o cadastro de pessoal.", ROTA_ADIANTAMENTOS),
  "5.10.2.26": m("VALIDADO_LOCALMENTE", "listarDiariasPublicas lê as concessões de diária a cada consulta, sem etapa de publicação, com CPF mascarado (lib/portas/diarias-publicas.ts; m05-adiantamentos.test.ts t5), em /transparencia/diarias.", ROTA_ADIANTAMENTOS),
  "5.10.2.27": m("PARCIAL", "o lote aceita vencimento e inclui ordem de pagamento ou nota extra, com ordem cronológica conferida (m09-lote.test.ts); tela /financeiro/lotes. FALTA: nota extra pela tela e percurso de inclusão, fechamento, borderô e retorno.", "/financeiro/lotes · scripts/smoke-ent03a.ts (só criação)."),
  "5.10.2.28": m("PARCIAL", "contasComSaldo dá saldo por conta e por fonte nas telas de movimentação, lotes e conciliação; o saque é barrado por saldo insuficiente (m09-movimentacao.test.ts). FALTA: o formulário de pagamento não mostra o saldo da conta nem da fonte."),
  "5.10.2.29": m("PARCIAL", "o lote agrupa ordens de pagamento e notas extras por referência (m09-lote.test.ts). FALTA: nota extra pela tela, prova de ordem de resto no lote e percurso de inclusão."),
  "5.10.2.30": m("VALIDADO_LOCALMENTE", "o vencimento vem da ordem de pagamento e do lote; /despesa/a-pagar o mostra e exporta (m05-a-pagar.test.ts t1); a ordem cronológica é guard no pagamento e no lote (m06-pagamento.test.ts, m06-fila-parcial.test.ts, m09-lote.test.ts t6, t7). Ressalva: sem ordem, sem vencimento.", "/despesa/a-pagar, /despesa/ordem-cronologica · percursos scripts/percurso-v33.ts, scripts/percurso-v33-cadeias.ts."),
  "5.10.2.31": m("IMPLEMENTADO_NAO_VALIDADO", "gerarBordero gera o borderô de lote fechado (uma conta, vários itens e credores), com hash, anexo e fila de assinatura (m09-lote.test.ts t9 a t13); tela /financeiro/lotes. FALTA: percurso até a geração; o envio ao banco é indisponível (5.10.2.34)."),
  "5.10.2.32": m("AUSENTE_CONFIRMADO", "não há leitura de arquivo de retorno bancário (CNAB); processarRetornoBancario baixa itens marcados à mão."),
  "5.10.2.33": m("PARCIAL", "processarRetornoBancario grava a baixa idempotente por item (m09-lote.test.ts t14, t15). FALTA: a baixa não cria o pagamento nem o lançamento, vem de marcação manual e não tem percurso."),
  "5.10.2.34": m("AUSENTE_CONFIRMADO", "enviarBordero recusa sempre, nomeando a falta de convênio bancário (BORDERO-CONVENIO-BANCARIO); não há configuração de baixar na geração do borderô."),
  "5.10.2.35": m("VALIDADO_LOCALMENTE", "/despesa/pagamentos lista os pagamentos com situação e oferece estorno total ou parcial com lançamento novo (m05-anulacao-parcial.test.ts t3 a t5); restos têm a mesma operação em tela própria (smoke-restos-a-pagar-operacoes.ts).", "/despesa/pagamentos · percurso scripts/smoke-cadeia-despesa.ts (anula pela tela e reencontra após recarga)."),
  "5.10.2.36": m("PARCIAL", "/despesa/a-pagar lista as obrigações por credor; desde a V36 filtra também por fonte e por vencimento ('vence até', da ordem de pagamento; obrigação sem ordem fica fora e a tela diz isso), na tela e no PDF (lib/portas/a-pagar.ts). FALTA: selecionar vários e pagar de uma vez (o lote de pagamentos do M09 é o caminho para isso).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-a-pagar.mts, 7/7"),
  "5.10.2.38": m("PARCIAL", "a ordem de pagamento autorizada (modules/m05-despesa/ordem-pagamento.ts; m05-ordem-pagamento.test.ts) é consumida pelo pagamento no select 'Ordem autorizada', e grava dataPrevista. FALTA: filtrar as ordens por data de vencimento e pagar várias de uma vez.", "/despesa/ordens, /despesa/pagamentos · scripts/smoke-cadeia-despesa.ts."),
  "5.10.2.39": m("IMPLEMENTADO_NAO_VALIDADO", "pagamento total e parcial pelo campo valor, com teto no liquidado lido da soma real (m05b.test.ts); estorno total e parcial do pagamento como registro novo (m05-anulacao-parcial.test.ts t3; parcial com retenção recusado com motivo, t4). FALTA: percurso de pagamento parcial e estorno parcial pela tela (o percurso paga e estorna o total)."),
  "5.10.2.40": m("VALIDADO_LOCALMENTE", "modo diferente, mesmo efeito: os lançamentos do pagamento são consultados no dossiê do empenho (dossie.ts, seção de lançamentos, com caixa e retenção) e o estorno parte do pagamento, gerando os lançamentos invertidos com o original mantido (m05-dossie.test.ts: estorno devolve 900, não 1.000; m05-anulacao-parcial.test.ts t8).", "/despesa/empenhos/[id], /despesa/pagamentos · percursos scripts/smoke-cadeia-despesa.ts (paga com retenção, confere o dossiê, anula, recarrega) e scripts/percurso-v31-rastreio.ts."),
  "5.10.2.41": m("PARCIAL", "a ordem de pagamento existe para liquidação de empenho do exercício, com preparar, autorizar por outra pessoa e cancelar (/despesa/ordens). FALTA: ordem para restos a pagar (pagos sem ordem pelo M08), ordem para despesa extraorçamentária e inclusão de nota extra no lote pela tela.", "/despesa/ordens · scripts/smoke-cadeia-despesa.ts."),
  "5.10.2.42": m("AUSENTE_CONFIRMADO", "não há cheque: Pagamento não guarda meio nem número de cheque, e não existe cheque avulso nem consulta."),
  "5.10.2.44": m("PARCIAL", "importação do extrato OFX pela tela da conciliação (/financeiro/conciliacao), idempotente, decodificando pelo charset do cabeçalho. V36: o leitor (packages/ofx) foi conferido contra uma implementação independente (o algoritmo da finsystem) sobre DEZ extratos reais de 2026 — Itaú, SGML sem fechamento, e Sicredi, folhas fechadas —: 2.309 lançamentos, concordância linha a linha em FITID, data, sinal e centavos (medição local; os arquivos não entram no repositório). Arquivo .ofc com conteúdo OFX é aceito; PDF, ZIP/planilha, página salva e o leiaute OFC próprio são recusados com o motivo (ofx.test.ts). E o extrato não entra na conta errada: BANKID contra o banco da conta, ACCTID ligado à conta na primeira importação, e o mesmo arquivo em outra conta recusado — antes respondia \"já importado\" nomeando a conta errada (modules/m09-tesouraria/extrato.ts; m09-extrato-conta-do-arquivo.test.ts, 5/5, duas mutações). E a impressão do extrato importado: /financeiro/conciliacao/extratos lista os extratos do exercício e mostra as linhas como o banco as mandou, com créditos, débitos, movimento do arquivo e a situação de cada linha na conciliação derivada dos vínculos vivos, e imprime em PDF (/financeiro/conciliacao/extratos/pdf; modules/m09-tesouraria/extrato-importado.ts; m09-extrato-importado.test.ts, 3/3, três mutações — regra da conciliada, ordem natural do identificador, estorno do vínculo). FALTA: o leiaute OFC próprio (raiz <OFC>) — sem arquivo real nem especificação, não se escreve leitor de memória.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percursos scripts/percurso-v36-importar-extrato.mts (3/3) e scripts/percurso-v36-extrato-da-conta-certa.mts (4/4: outro banco, mesmo arquivo em outra conta, .ofc com OFX lido, leiaute OFC recusado) e scripts/percurso-v36-extratos-importados.mts (5/5: lista sem o número cru da conta, linhas e totais iguais ao leitor do M09, PDF 200 e inexistente 404 com motivo, usuário sem a leitura do financeiro levado a /sem-acesso e PDF 403)."),
  "5.10.2.50": m("VALIDADO_LOCALMENTE", "V36: a tela da conciliação (/financeiro/conciliacao) filtra por período (dia civil), histórico/documento/FITID (sem caixa nem acento), valor (sem sinal, como digitado; valor ilegível é avisado e ignorado) e tipo do registro interno (o controle do lançamento: pagamento, arrecadação, extraorçamentário, movimentação, transferência), nas correspondências e nas duas pendências; recorte de exibição — a soma do motor permanece e a soma das linhas exibidas aparece ao lado (app/(areas)/financeiro/conciliacao/filtro.ts; test/ui/conciliacao-filtro.test.ts).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-conciliacao-filtros.mts, 4/4."),
  "5.10.2.51": m("VALIDADO_LOCALMENTE", "V36: ordem pela coluna de valor, crescente ou decrescente, com sinal e em Decimal, dos dois lados (extrato e lançamentos) e nas correspondências; empate mantém a ordem por data (filtro.ts; test/ui/conciliacao-filtro.test.ts).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-conciliacao-filtros.mts: as linhas exibidas vêm na ordem pedida nos dois sentidos."),
  "5.10.2.52": m("PARCIAL", "a baixa praticada é o vínculo extrato x razão em /financeiro/conciliacao, com desfazer e motivo (m09-conciliacao.test.ts, m09-conciliacao-periodo.test.ts); o serviço calcula 'resolvida' para pendência manual. FALTA: a tela não separa baixadas de abertas e nenhum serviço resolve pendência manual."),
  "5.10.2.53": m("VALIDADO_LOCALMENTE", "a conciliação do período mostra saldos, diferença e pendências; desde a V36 o relatório sai em PDF (/financeiro/conciliacao/periodo/pdf): saldos, linhas sem vínculo dos dois lados com a justificativa, herdadas e declaradas; recusa do motor vira 409 com o motivo (lib/pdf/conciliacao.ts; test/ui/conciliacao-pdf.test.ts, N=2 por lado).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-conciliacao-pdf.mts: período aberto pela tela, PDF emitido."),
  "5.10.2.54": m("VALIDADO_LOCALMENTE", "modo diferente, mesmo efeito: o estorno parte do pagamento e os lançamentos invertidos nascem dele, consultáveis no dossiê do empenho (m05-dossie.test.ts); o lançamento manual tem estorno próprio em /contabilidade.", "/despesa/pagamentos, /despesa/empenhos/[id] · percursos scripts/smoke-cadeia-despesa.ts e scripts/demonstracao/percurso-lancamento-e-conciliacao.ts."),
  "5.10.2.56": m("IMPLEMENTADO_NAO_VALIDADO", "modo diferente: o documento de pagamento é o borderô gerado do lote fechado, com hash e fila de assinatura (servico-lote.ts; m09-lote.test.ts t9 a t13). FALTA: tela onde os signatários assinem o borderô (/despesa/assinaturas lista só empenho, liquidação e ordem), link de download e percurso."),
  "5.10.2.57": m("IMPLEMENTADO_NAO_VALIDADO", "enviarBordero confere as assinaturas antes de tudo e trata fila vazia como incompleta (m09-lote.test.ts t11 a t13, t16); sem convênio, recusa como indisponível com motivo. FALTA: colher as assinaturas do borderô pela tela e percurso; a transmissão depende de convênio bancário."),
  "5.10.2.58": m("VALIDADO_LOCALMENTE", "V36: Relatórios › Movimento diário (/relatorios/movimento-diario?dia=): a receita arrecadada no dia por natureza e fonte (arrecadadoPorNaturezaFonte do M04 na janela civil do dia, líquida das anulações) e a despesa paga no dia, do exercício e de restos, com retido e líquido (pagamentosEfetuados); PDF do mesmo recorte, dia malformado recusado com 400. lib/portas/receita-e-despesa-do-periodo.ts, lib/pdf/movimento-diario.ts. Modo de execução: a despesa realizada é a PAGA no dia (a realização financeira); empenho e liquidação do dia estão nas consultas da execução.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-receita-e-diario.mts: pago do dia e receita do dia batem com leituras independentes do domínio; PDF 200."),
  "5.10.2.59": m("PARCIAL", "/receita/arrecadacoes lista as guias do exercício com natureza, fonte e total, com CSV e PDF (m04-consultas-arrecadacao.test.ts); /transparencia/receitas filtra por fonte e período; arrecadadoPorFonte resume por fonte. FALTA: quadro mês a mês e o resumo por fonte numa tela de relatório."),
  "5.10.2.60": m("VALIDADO_LOCALMENTE", "V36: Relatórios › Receita mês a mês (/relatorios/receita-mensal): a receita arrecadada por fonte de recursos, mês a mês, nos três últimos exercícios até o do contexto, com o total de cada ano e a planilha (CSV). modules/m04-receita/arrecadado-mes-a-mes.ts compõe arrecadadoPorNaturezaFonte por mês (sinal da anulação e guia repartida de lá); m04-arrecadado-mes-a-mes.test.ts (duas fontes, dois exercícios, hora de borda na virada do mês, anulação no mês dela; mutação para janela UTC acusada).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-receita-e-diario.mts: o total de 2026 da tela bate com listarArrecadacoes (R$ 2.787.852,25)."),
  "5.10.2.61": m("VALIDADO_LOCALMENTE", "V36: Relatórios › Ficha do credor (/relatorios/credor): numa página, os empenhos do exercício com empenhado líquido, liquidado e pago; o que está a liquidar e a pagar, do exercício e de restos, com vencimento; e os pagamentos efetuados no exercício com retido e líquido — cada bloco pela leitura da tela própria dele (listarEmpenhosDaExecucao, lerAPagar, lerPagamentosEfetuados; lib/portas/ficha-do-credor.ts), com o link para a tela completa já filtrada, e o nome do credor no a pagar levando à ficha.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-ficha-do-credor.mts, 5/5: a ficha concorda com o relatório de pagamentos (14 linhas, líquido), com a tela do a pagar (os dois totais) e com o banco (18 empenhos)."),
  "5.10.2.62": m("PARCIAL", "integração interna: o lançamento tributário constituído vira receita reconhecida no M04 pelo roteiro (test/lancamento-tributario.test.ts), a arrecadação baixa o crédito (m04-reconhecimento.test.ts t1, t2, t8), o cancelamento baixa por VPD e há inscrição em dívida ativa. FALTA: recolhimento da rede bancária, anistia, isenção e prescrição como tipos próprios, e percurso."),
  "5.10.2.63": m("PARCIAL", "/receita/lancamentos/[loteId] mostra o lote com as inconsistências por lançamento antes de constituir, e constituir com inconsistência é recusado (test/lancamento-tributario.test.ts). FALTA: relatório de críticas emissível e conferência prévia da configuração contábil das receitas."),
  "5.10.2.64": m("AUSENTE_CONFIRMADO", "não há restituição de receita (ano anterior por empenho, ano corrente por dedução); a dedução existente é só a do FUNDEB e a anulação de arrecadação não distingue o exercício."),
  "5.10.2.66": m("PARCIAL", "o mecanismo geral por fonte existe: arrecadação com natureza e fonte, despesa com a fonte da ficha, guard da fonte da conta (m05b.test.ts), e publicação automática por fonte em /transparencia/receitas e /transparencia/despesas. FALTA: a vinculação declarada multa de trânsito x fonte x despesa e a publicação dedicada."),
  "5.10.2.67": m("PARCIAL", "mesma exigência da 5.10.2.36: /despesa/a-pagar filtra por credor, fase, origem e, desde a V36, fonte e vencimento. FALTA: pagamento simultâneo de vários registros.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio com a etapa financeira do semeador, 2026-10-05 · percurso scripts/percurso-v36-a-pagar.mts, 7/7"),
  "5.10.2.68": m("VALIDADO_LOCALMENTE", "V36: o Anexo do M22 ganhou os donos pagamento e movimento bancário (migration aditiva 20261106130000, duas colunas anuláveis; o dono único continua no zAnexar). O anexo do pagamento segue a UG do pagamento (escopo { pagamento } do M16), o do movimento é ato do ente; o download cobra a leitura do dono (despesa na unidade do pagamento; financeiro do ente). modules/m22-documentos/m22-anexo-do-pagamento-e-do-movimento.test.ts 4/4 (N=2 anexos e donos; quem anexa só noutra unidade é recusado no pagamento; permissão de unidade não basta no movimento; dono inexistente ou duplo recusado com o motivo), três mutações acusadas. Tela: na lista de pagamentos realizados (/despesa/pagamentos), o link \"documentos\" abre /despesa/pagamentos/[id], com o registro, os anexos e o formulário de anexar.", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-anexos-do-pagamento.mts: PDF anexado ao pagamento, gravado, listado depois de recarregar e baixado (200, application/pdf)."),
  "5.10.2.70": m("VALIDADO_LOCALMENTE", "modo diferente, equivalente: ao enviar o documento para assinatura o operador escolhe os signatários e a ordem (FormEnviarAssinatura); a fila é ordenada e quem fura a ordem é recusado com motivo (m05-assinatura-da-despesa.test.ts t4, t9; m22-documentos.test.ts t12, t13). A configuração é por documento, não cadastro permanente. A assinatura qualificada é recusada com motivo (sem certificado ICP-Brasil).", "/despesa/assinaturas · percurso scripts/smoke-ent03a.ts (envia, assina, recarrega)."),
  "5.10.2.71": m("VALIDADO_LOCALMENTE", "V36: Relatórios › Pagamentos efetuados (/relatorios/pagamentos), do exercício e de restos a pagar, por período, com filtros de credor, fonte e conta bancária, agrupamento por credor, fonte ou conta com subtotais, opção de listar ou não as retenções, CSV e PDF do mesmo recorte. modules/m05-despesa/pagamentos-efetuados.ts (liquidoDoFato e retidoPorPagamento, sem segunda aritmética); m05-pagamentos-efetuados.test.ts (retenção viva e estornada, pagamento anulado, resto pago em 2027; duas mutações acusadas).", "papel: administrador · contexto: next dev na 3011, banco gestao_publica_esperanca_ficticio, 2026-10-06 · percurso scripts/percurso-v36-pagamentos-efetuados.mts, 7/7 (30 pagamentos; pago − retido = líquido; conta, período e agrupamento conferidos; PDF)."),
  "5.10.2.72": m("AUSENTE_CONFIRMADO", "não há portal do fornecedor com usuário e senha; a posição a pagar por credor existe só para o operador interno."),
};
