/**
 * O ROTEIRO DA APRESENTAÇÃO DA CONTABILIDADE (V22) — uma tela por requisito do termo de
 * referência, na ordem em que se apresenta. Compartilhado pelo conferidor de telas (abre com
 * conteúdo) e pelo conferidor de ações (os links, exportações, janelas e filtros de cada tela
 * respondem).
 */
export const ROTEIRO: readonly (readonly [string, string])[] = [
  ["Registro contábil — lançamentos", "/contabilidade/lancamentos"],
  ["Centros de custo", "/contabilidade/custos"],
  ["Diário", "/relatorios/livros/diario"],
  ["Razão (conta de caixa)", "/relatorios/livros/razao?conta=1.1.1.1.1.19.00"],
  ["Balancete", "/relatorios/livros/balancete"],
  ["Balanço orçamentário", "/relatorios/demonstracoes/balanco-orcamentario"],
  ["Balanço financeiro", "/relatorios/demonstracoes/balanco-financeiro"],
  ["Balanço patrimonial", "/relatorios/demonstracoes/balanco-patrimonial"],
  ["Variações patrimoniais", "/relatorios/demonstracoes/variacoes-patrimoniais"],
  ["Fluxos de caixa (DFC)", "/relatorios/demonstracoes/fluxos-de-caixa"],
  ["Arquivos para a STN e a Receita", "/contabilidade/exportacoes-federais"],
  ["Responsáveis técnicos", "/contabilidade/exportacoes-federais/responsaveis"],
  ["Classificação para o arquivo da Receita", "/contabilidade/exportacoes-federais/classificacao"],
  ["RREO anexo 1", "/relatorios/rreo/anexo1"],
  ["RREO anexo 3 (RCL)", "/relatorios/rreo/anexo3?exercicio=2026&bimestre=5"],
  ["RREO anexo 8 (MDE)", "/relatorios/rreo/anexo8?exercicio=2026&bimestre=5"],
  ["RREO anexo 12 (saúde)", "/relatorios/rreo/anexo12?exercicio=2026&bimestre=5"],
  ["RGF anexo 1 (pessoal)", "/relatorios/rgf/anexo1?exercicio=2026&quadrimestre=2"],
  ["PPA", "/planejamento/ppa"],
  ["LDO", "/planejamento/ldo"],
  ["Lei Orçamentária Anual", "/planejamento/loa"],
  ["Fichas da LOA", "/planejamento/fichas"],
  ["QDD", "/planejamento/qdd"],
  ["Alterações de PPA/LDO", "/planejamento/alteracoes"],
  ["Unidades orçamentárias", "/planejamento/unidades-orcamentarias"],
  ["CMD e MBA", "/planejamento/cmd-mba"],
  ["Créditos adicionais", "/planejamento/creditos-adicionais"],
  ["Remanejamento, transposição e transferência", "/planejamento/realocacoes"],
  ["Processos (reserva de dotação)", "/licitacoes/processos"],
  ["Solicitações de compra", "/licitacoes/solicitacoes"],
  ["Contratos", "/licitacoes/contratos"],
  ["Solicitações de empenho", "/despesa/solicitacoes-de-empenho"],
  ["Campanhas publicitárias", "/despesa/campanhas-publicitarias"],
  ["Empenhos", "/despesa/empenhos"],
  ["Liquidações", "/despesa/liquidacoes"],
  ["Pagamentos", "/despesa/pagamentos"],
  ["Assinaturas", "/despesa/assinaturas"],
  ["Restos a pagar", "/despesa/restos-a-pagar"],
  ["Naturezas de receita", "/receita/naturezas"],
  ["Arrecadação", "/receita/arrecadacoes"],
  ["Extraorçamentário", "/financeiro/extraorcamentario"],
  ["Retenções a recolher", "/financeiro/extraorcamentario/recolher"],
  ["Convênios", "/transferencias/convenios"],
  ["Natureza das fontes", "/contabilidade/natureza-das-fontes"],
  ["Eliminações intragovernamentais", "/relatorios/eliminacoes-intra"],
];
