-- CreateEnum
CREATE TYPE "AcaoDoSistema" AS ENUM ('REGISTRAR_LANCAMENTO_MANUAL', 'ESTORNAR_LANCAMENTO_MANUAL', 'CRIAR_FICHA', 'CRIAR_RECEITA_PREVISTA', 'CRIAR_LEI_DE_CREDITO', 'CRIAR_DECRETO_DE_CREDITO', 'EXECUTAR_CREDITO', 'ANULAR_CREDITO', 'ENCERRAR_DECRETO', 'REGISTRAR_ARRECADACAO', 'ANULAR_ARRECADACAO', 'RESERVAR_DOTACAO', 'LIBERAR_RESERVA', 'EMPENHAR', 'ANULAR_EMPENHO', 'ANULAR_EMPENHO_PARCIAL', 'LIQUIDAR', 'ANULAR_LIQUIDACAO', 'ANULAR_LIQUIDACAO_PARCIAL', 'PAGAR', 'ANULAR_PAGAMENTO', 'ANULAR_PAGAMENTO_PARCIAL', 'ESTORNAR_ANULACAO_PARCIAL', 'REGISTRAR_INGRESSO_EXTRA', 'REGISTRAR_DISPENDIO_EXTRA', 'ESTORNAR_MOVIMENTO_EXTRA', 'ABRIR_EXERCICIO', 'ENCERRAR_EXERCICIO', 'APURAR_RESULTADO', 'ESTORNAR_APURACAO', 'ENCERRAR_CONTROLES_ORCAMENTARIOS', 'ESTORNAR_ENCERRAMENTO_CONTROLES', 'LIQUIDAR_RESTOS_A_PAGAR', 'PAGAR_RESTOS_A_PAGAR', 'CANCELAR_RESTOS_A_PAGAR', 'ANULAR_PAGAMENTO_RESTOS_A_PAGAR', 'ANULAR_CANCELAMENTO_RESTOS_A_PAGAR', 'IMPORTAR_EXTRATO', 'VINCULAR_CONCILIACAO', 'ESTORNAR_VINCULO', 'CADASTRAR_CLASSE_DE_MATERIAL', 'REGISTRAR_ENTRADA_ALMOXARIFADO', 'REGISTRAR_SAIDA_CONSUMO', 'REGISTRAR_AJUSTE_ALMOXARIFADO', 'ESTORNAR_MOVIMENTO_ALMOXARIFADO', 'ADQUIRIR_BEM', 'REGISTRAR_ENTRADA_AVULSA', 'ALIENAR_BEM', 'BAIXAR_BEM', 'REGISTRAR_REAVALIACAO', 'REGISTRAR_IMPAIRMENT', 'REGISTRAR_CUSTO_SUBSEQUENTE', 'ATUALIZAR_COMPETENCIA_PATRIMONIAL', 'ESTORNAR_MOVIMENTO_PATRIMONIAL', 'CADASTRAR_DIVIDA', 'REGISTRAR_ATUALIZACAO_MONETARIA', 'ESTORNAR_MOVIMENTO_DIVIDA', 'CADASTRAR_DIVIDA_ATIVA', 'INSCREVER_DIVIDA_ATIVA', 'ATUALIZAR_DIVIDA_ATIVA', 'CANCELAR_DIVIDA_ATIVA', 'ESTORNAR_MOVIMENTO_DIVIDA_ATIVA', 'CADASTRAR_PROVISAO', 'CONSTITUIR_PROVISAO', 'REVERTER_PROVISAO', 'ATUALIZAR_PROVISAO', 'ESTORNAR_MOVIMENTO_PROVISAO', 'CADASTRAR_PROCESSO', 'HOMOLOGAR_PROCESSO', 'CADASTRAR_CONTRATO', 'REGISTRAR_ADITIVO', 'ESTORNAR_MOVIMENTO_CONTRATUAL', 'CADASTRAR_LIMITE', 'CADASTRAR_OBRA', 'CADASTRAR_LINHA_DEMONSTRATIVO', 'TRAVAR_COMPETENCIA', 'DESTRAVAR_COMPETENCIA');

-- CreateTable
CREATE TABLE "Usuario" (
    "id" TEXT NOT NULL,
    "identificador" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "criadoPor" TEXT NOT NULL,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Usuario_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Perfil" (
    "id" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "criadoPor" TEXT NOT NULL,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Perfil_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PermissaoDePerfil" (
    "id" TEXT NOT NULL,
    "perfilId" TEXT NOT NULL,
    "acao" "AcaoDoSistema" NOT NULL,
    "unidadeOrcId" TEXT,
    "criadoPor" TEXT NOT NULL,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PermissaoDePerfil_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VinculoUsuarioPerfil" (
    "id" TEXT NOT NULL,
    "usuarioId" TEXT NOT NULL,
    "perfilId" TEXT NOT NULL,
    "criadoPor" TEXT NOT NULL,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "VinculoUsuarioPerfil_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Usuario_identificador_key" ON "Usuario"("identificador");

-- CreateIndex
CREATE INDEX "Usuario_ativo_idx" ON "Usuario"("ativo");

-- CreateIndex
CREATE UNIQUE INDEX "Perfil_nome_key" ON "Perfil"("nome");

-- CreateIndex
CREATE INDEX "PermissaoDePerfil_perfilId_idx" ON "PermissaoDePerfil"("perfilId");

-- CreateIndex
CREATE INDEX "PermissaoDePerfil_acao_idx" ON "PermissaoDePerfil"("acao");

-- CreateIndex
CREATE UNIQUE INDEX "PermissaoDePerfil_perfilId_acao_unidadeOrcId_key" ON "PermissaoDePerfil"("perfilId", "acao", "unidadeOrcId");

-- CreateIndex
CREATE INDEX "VinculoUsuarioPerfil_usuarioId_idx" ON "VinculoUsuarioPerfil"("usuarioId");

-- CreateIndex
CREATE UNIQUE INDEX "VinculoUsuarioPerfil_usuarioId_perfilId_key" ON "VinculoUsuarioPerfil"("usuarioId", "perfilId");

-- AddForeignKey
ALTER TABLE "PermissaoDePerfil" ADD CONSTRAINT "PermissaoDePerfil_perfilId_fkey" FOREIGN KEY ("perfilId") REFERENCES "Perfil"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PermissaoDePerfil" ADD CONSTRAINT "PermissaoDePerfil_unidadeOrcId_fkey" FOREIGN KEY ("unidadeOrcId") REFERENCES "UnidadeOrcamentaria"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VinculoUsuarioPerfil" ADD CONSTRAINT "VinculoUsuarioPerfil_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES "Usuario"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VinculoUsuarioPerfil" ADD CONSTRAINT "VinculoUsuarioPerfil_perfilId_fkey" FOREIGN KEY ("perfilId") REFERENCES "Perfil"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
