-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_DEPOSITO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_UNIDADE_DE_MEDIDA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_GRUPO_DE_MATERIAL';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CADASTRAR_MATERIAL';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'DEFINIR_PARAMETRO_DE_ESTOQUE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_ENTRADA_FISICA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_SAIDA_FISICA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ESTORNAR_MOVIMENTO_FISICO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'TRANSFERIR_ENTRE_DEPOSITOS';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_REQUISICAO_DE_MATERIAL';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'DEFINIR_COTA_DE_CONSUMO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ABRIR_INVENTARIO_DE_ESTOQUE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'REGISTRAR_CONTAGEM_DE_INVENTARIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'FECHAR_INVENTARIO_DE_ESTOQUE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'BLOQUEAR_ESTOQUE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'ENCERRAR_BLOQUEIO_DE_ESTOQUE';
