-- AlterEnum
--
-- Orquestração V3, 4.1 — a LEITURA entra no censo: uma ação CONSULTAR_<ÁREA> por área de
-- navegação, concedida global ou por unidade gestora como qualquer outra ação.
--
-- ADITIVA: `ALTER TYPE ... ADD VALUE` não remove nem renomeia nada. Zero DROP. Um valor
-- por instrução (a limitação do PostgreSQL <= 11 que a migration do ENT07 documenta).
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_PLANEJAMENTO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_RECEITA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_DESPESA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_FINANCEIRO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_PATRIMONIO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_LICITACOES';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_CONTABILIDADE';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_RELATORIOS';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_TRANSPARENCIA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_PROTOCOLO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_COMUNICACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_CADASTROS';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_TRANSFERENCIAS';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_DIVIDA';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_CONTROLE_INTERNO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_ADMINISTRACAO';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_INTEGRACOES';
ALTER TYPE "AcaoDoSistema" ADD VALUE 'CONSULTAR_SUPORTE';
